// Period essays, part 1 (periods 01-06).
const A = {
  quarry: {
    lede: 'Before there was a church, a basilica, a temple, a garden or a tomb, there was a hole in the ground where men cut stone.',
    paras: [
      { h: 'A hillside made of the right kind of rock' },
      { text: 'Jerusalem sits on limestone, and not all limestone is equal. The layer the builders wanted is called meleke, an Arabic word meaning "royal" or "kingly." Meleke is unusual stuff. Underground, protected from the air, it is soft enough to cut with a hand pick — a strong quarryman can score a channel through it the way you can cut cheese with a wire. Once it is out in the sun and the wind, it hardens over a few seasons into a durable, creamy white building stone that takes a fine edge and weathers to a warm gold.' },
      { text: 'A city that wanted monumental buildings needed meleke, and a great deal of it. The slope that we now call the site of the Holy Sepulchre had a thick, clean bed of it lying close to the surface. From at least the eighth century BCE, and possibly earlier, people came here to take it out.' },
      { h: 'What a quarry actually looked like' },
      { text: 'Ancient quarrying was not blasting or smashing. It was patient, geometric work. A quarryman marked out a rectangle on the exposed rock surface, roughly the size of the block he wanted. Then he cut a narrow channel — usually about a hand\'s width — all the way around it and down its sides, kneeling in the trench as it deepened. When the block was free on four sides, he drove wooden or metal wedges into the seam at its base and levered it up. If he was lucky, it came away clean.' },
      { text: 'This method leaves an unmistakable signature: a floor covered in shallow rectangular scars, like the imprint of bricks lifted out of wet sand, with the last unfinished block sometimes still sitting in its channel where the work stopped. Faces cut back into the hillside — archaeologists call them scarps — carry vertical tool marks in long, regular strokes. Both survive at this site, and both are now visible in the excavation trenches beneath the church floor.' },
      { text: 'Because quarrying moves downwards as well as sideways, a large quarry ends up terraced. The plan on the left shows three working levels: an upper floor closest to the original hillside, a middle floor stepped down about two metres, and a deeper floor to the west, beneath what is now the rotunda. That deepest floor is the surface that the current excavation team from Sapienza University of Rome reached in 2022.' },
      { h: 'What the diggers found' },
      { text: 'For most of the twentieth century the archaeology of this site was done in fragments — a trench here when a wall was underpinned, a look there when a floor cracked. The six Christian communities who share the church could rarely agree to let anyone lift the paving. That changed in 2022, when a long-planned repair of the floor gave archaeologists a rare licence to dig properly, room by room, while the church stayed open to pilgrims.' },
      { text: 'Under the rotunda they found the quarry floor. Not a hint of it, not a suggestive slope: the actual working surface, with cut beds in it. Pottery from the fill above it runs back into the Iron Age, which means people were taking stone out of this hillside in the centuries of the kings of Judah — the world of Hezekiah and Isaiah, hundreds of years before anything that happens later on this page.' },
      { h: 'The block nobody wanted' },
      { text: 'Quarries are shaped as much by the bad rock as the good. Meleke is not uniform; it is threaded with cracks, soft pockets and seams of flint. When a quarryman hit a flawed mass, he did not waste weeks on stone that would split on the mason\'s bench. He cut around it and left it standing while the floor dropped away on every side.' },
      { text: 'Near the south-eastern edge of this quarry, one such mass was left: a lump of cracked rock, perhaps six or seven metres high once the ground around it had gone, standing above the working floor like a stump in a felled wood. Nobody who left it there thought anything of it. It was simply rubbish stone.' },
      { text: 'That rock is Golgotha.' },
      { text: 'It is worth sitting with how ordinary that is. There was no shrine, no marker, no sense that anything had happened here. A stonecutter looked at a flawed lump, swore at it, and worked around it. The rock survived because it was not worth destroying.' },
      { h: 'What the work was like' },
      { text: 'Quarrying was a trade, and a hard one. The men who did it worked in the open, in a hollow that trapped heat in summer and filled with dust whenever a block came free. The tools were simple: iron picks of various weights, wedges, levers, wooden sledges and rollers, and rope. A single block of the size used in monumental building could weigh a couple of tonnes.' },
      { text: 'The rhythm of the work explains the shape of the ground. You cut where the rock was good and you followed the good rock downward, which is why the floor steps rather than slopes. You worked back into the hill rather than out into the open, because a face gives you leverage and open ground does not. Every feature on this plan is the fossil of a decision somebody made about where the next block should come from.' },
      { h: 'Outside the city' },
      { text: 'One more thing on the plan matters enormously for everything that follows. This quarry is outside Jerusalem. Nobody quarries inside a walled city if they can help it — the noise, the dust, the carts and the sheer space required all argue for working beyond the gate and hauling the blocks in. The city walls of this period lie roughly 250 metres to the south and east, and the traffic of loaded sledges would have run downhill towards the Gennath Gate.' },
      { text: 'By the end of the Hellenistic period the stone here was worked out, or at least no longer worth the effort. The quarry was abandoned. Soil began to blow and wash into the hollow, filling the lower floors, softening the cut edges, collecting in the corners where nothing drained. Weeds came, then bushes. A big, awkward, stepped hole in the ground just outside the city wall, with good deep soil settling on its floor and vertical rock faces on its western side, was about to become useful for two entirely different purposes at once.' }
    ],
    debates: [
      'The start date of quarrying is not fixed. Iron Age pottery in the fill proves activity by the 8th–7th centuries BCE, but pottery can be residual — carried in later with the soil. Some argue for a mainly Hellenistic quarry with earlier material mixed in.',
      'How far the quarry extended north and west is unknown. The plan\'s outer edge is drawn from the rock faces actually recorded inside the church and in neighbouring cellars; beyond those points it is projection.'
    ],
    facts: [['Rock', 'Meleke limestone'], ['Evidence', 'Quarry floors, cut beds, tool marks'], ['Dug', 'Sapienza University, 2022–']]
  },

  garden: {
    lede: 'An abandoned quarry with soil in its bottom and clean rock faces on its side is, to a first-century family, two things at once: a place to plant and a place to bury.',
    paras: [
      { h: 'The garden' },
      { text: 'It sounds odd to plant a garden in a quarry until you think about what a worked-out quarry offers. The floor has been cut flat. Windblown and washed-in soil collects there and stays, because there is nowhere for it to go. The rock walls hold the day\'s heat and shelter the plants from wind. Terraced ground like this, just outside a city gate, is prime market-garden land.' },
      { text: 'This is not a guess made to fit a Gospel line. The excavations begun in 2022 recovered plant remains from the soil layers that formed on the quarry floor: seeds, pollen and traces consistent with olives, vines and cereals. The ground was cultivated. Someone worked it.' },
      { text: 'That matters, because it is the sort of small, undramatic detail that no one would invent. The Gospel of John says that the place where Jesus was crucified had a garden nearby, and in the garden a new tomb. For centuries that was either taken on faith or dismissed as a literary flourish. The soil says there was, in fact, a garden.' },
      { h: 'Tombs in the western face' },
      { text: 'The other thing a quarry gives you is a vertical wall of workable rock, already exposed, already stripped of topsoil. In Jerusalem in the last century BCE and the first century CE, that is exactly what a family needed if they were going to cut a tomb.' },
      { text: 'Jewish burial around Jerusalem at this time followed a particular pattern. A family cut a chamber into rock, entered through a low doorway you had to stoop or crawl through. Inside, the body was laid out, wrapped and spiced, and left for about a year. When only bones remained, they were gathered up and placed in a limestone box — an ossuary — and the shelf was free for the next death. A tomb was not a single grave but a family\'s slow, reusable cupboard of the dead.' },
      { text: 'There were two main ways to make the space for a body. A kokh (plural kokhim) is a narrow tunnel driven straight back into the wall, roughly the length and width of a person, so that the body goes in head-first like a loaf into an oven. An arcosolium is grander and later: a shelf cut lengthways along the wall with an arch carved over it, so the body lies parallel to the room and can be seen. Arcosolium tombs took more work, and generally belonged to people with more money.' },
      { text: 'Two more details turn up constantly in the sources. The low doorway was not poor workmanship; it was deliberate, to make the opening easier to block and harder for animals to enter. And a tomb was almost never a solitary thing — cutting a chamber into rock took weeks of paid labour, so a family that could afford one used it for generations.' },
      { text: 'This is why the Gospel phrase about a tomb "in which no one had yet been laid" is striking rather than incidental. A brand-new, unused tomb belonging to a wealthy man, standing empty at the moment it was needed, was an unusual thing, and an expensive favour.' },
      { text: 'One last thing about this ground. Everything described here — the garden soil, the tomb doorways, the cut rock faces — was on open view in the first century. Anyone walking out of the city gate could see it. Within a hundred years all of it was underground, and it stayed underground for two centuries. The site did not survive because anyone protected it. It survived because it was buried by people who did not care what was down there.' },
      { h: 'The two tombs you can still visit' },
      { text: 'At least half a dozen tombs were cut into the faces of this old quarry, and pieces of several of them survive inside the church today.' },
      { text: 'On the western edge of the rotunda, behind the Edicule and reached through a scruffy doorway in the Syriac chapel, is a kokhim tomb with shafts radiating from a small chamber. It is unglamorous, half-ruined, and archaeologically priceless — it proves beyond argument that this ground was a first-century cemetery. Tradition calls it the Tomb of Joseph of Arimathea. That name is a later attachment; the tomb itself is real and datable.' },
      { text: 'And near the centre of what is now the rotunda was a second tomb, of the more expensive arcosolium type: a chamber with a shelf cut along one wall beneath an arch. It is that shelf, and the rock around it, that Constantine\'s builders would later isolate from the hillside, that al-Hakim\'s workmen would attack with picks, and that engineers would uncover for sixty hours in October 2016.' },
      { h: 'Reading the plan honestly' },
      { text: 'Look at the confidence marks on the drawing. The tombs shown in solid dark fill are secure: their rock survives and has been surveyed. The blocking stone at the tomb door is drawn as reconstructed, because we genuinely do not know its shape — large disc-shaped rolling stones are known in first-century Jerusalem but they are rare and usually belong to very wealthy tombs, while the ordinary stopper was a squared plug. Artists have drawn a rolling stone for so long that it feels like evidence. It is not.' },
      { h: 'Outside the wall — and why that is the whole argument' },
      { text: 'Executions and burials happened outside a city, not inside it. If this site was inside the walls in the first century, then it cannot be the place of the crucifixion, and the church is built over the wrong hill. That objection has been raised for two hundred years, and it is a fair one.' },
      { text: 'The answer depends on the course of the Second Wall, and here honesty is required: nobody knows where it ran. The historian Josephus tells us it started at the Gennath Gate and ran north to the Antonia fortress, but he does not say by what route, and the ground in between is buried under a living city. Every published map of the Second Wall is a hypothesis. The line on this plan is drawn dashed for that reason.' },
      { text: 'What can be said is this. The quarry is here, and quarries are extramural. The tombs are here, and Jewish law and custom put burial outside the walls. The garden soil is here, and market gardens belong outside the gate. Three independent kinds of evidence all say the same thing: in the first century, this ground lay outside Jerusalem. The wall, wherever it ran, ran east of it.' }
    ],
    debates: [
      'The course of the Second Wall is unresolved and probably unresolvable without excavation that cannot be done. Reconstructions differ by more than 100 m.',
      'Whether the venerated tomb was an arcosolium or a kokhim tomb has been argued for decades. The surviving rock is too damaged to settle it; the arcosolium reading is now the majority view.',
      'The identification of the western tomb with Joseph of Arimathea is traditional, not evidential. Its first-century date, however, is secure.'
    ],
    facts: [['Tomb type', 'Arcosolium (probable)'], ['Garden', 'Confirmed by seeds and pollen'], ['Wall line', 'Disputed']]
  },

  thirdwall: {
    lede: 'Within a decade or two of the crucifixion, the city grew north and swallowed the cemetery whole.',
    paras: [
      { h: 'A king in a hurry' },
      { text: 'Herod Agrippa I ruled Judaea for a very short time — roughly 41 to 44 CE — and spent a good part of it building. His most ambitious project was a new wall thrown around the whole northern suburb of Jerusalem, a district that had been spreading beyond the older defences for a generation. Josephus says the Romans grew nervous about how strong it was going to be and that Agrippa stopped short of finishing it; the work was completed hastily, decades later, in the run-up to the revolt of 66 CE.' },
      { text: 'The Third Wall runs well north of this plan — several hundred metres north — so the band across the top of the drawing is a symbol, not a survey. Its exact line is itself a long-running argument among archaeologists, with candidate stretches of masonry in the modern city defended and attacked for a century.' },
      { h: 'What changed on this patch of ground' },
      { text: 'The consequence for our site was immediate and legal. Jewish practice, backed by strong custom and by the sensibilities of a temple city, kept the dead outside the walls. Once the new wall enclosed this district, the cemetery here was finished. No new tombs would be cut. Existing tombs were sealed, and in time forgotten by everyone except the families who owned them and, if the tradition is right, one small group of people with a particular reason to remember one of them.' },
      { text: 'Land inside a city wall is worth more than land outside it. The old quarry hollow, with its garden soil and its awkward rock faces, was now urban real estate on the wrong side of nothing. Houses and workshops began to creep across the levelled parts. The plan shows them as probable, not secure: we have hints of first-century occupation debris in the fills, but no excavated house plans, because everything here was comprehensively rebuilt a century later.' },
      { h: 'A short window of memory' },
      { text: 'This period is short, and it is the hinge on which the whole question of authenticity swings. If a community in Jerusalem remembered where a particular tomb was, they had to hold that memory across just a few decades before the ground became inaccessible, and then across a much harder gap — the destruction of the city in 70 CE, the deportations, the second revolt under Bar Kokhba in 132–135, and the complete rebuilding of Jerusalem as a Roman colony.' },
      { text: 'It is worth being clear about what that means and what it does not. The site\'s defenders point out that Jerusalem\'s Christian community was not entirely dispersed, that a bishop list runs continuously through this period, and that a family memory of a burial place is exactly the kind of thing communities do preserve. Its critics point out that a century and a half is a long time, that the church tradition surfaces only in the 320s, and that the emperor who "found" the tomb had every political reason to find one.' },
      { text: 'Both are reasonable. What archaeology can say is narrower but still useful: whatever else is true, this was a real first-century tomb in a real first-century cemetery in the right kind of place, and it was buried under Roman fill within a hundred years of the crucifixion. That is not proof of identification. It is a good deal more than nothing.' },
      { h: 'The last ordinary years' },
      { text: 'For a generation this was simply a neighbourhood. Streets, houses, cisterns, the rubbish of daily life. The quarry faces became the back walls of yards. The tomb doors were plugged, plastered over or built against. Somewhere under a floor or behind a wall, the rock-cut chamber sat in the dark with its stone shelf, ordinary and unmarked.' },
      { h: 'A city growing too fast' },
      { text: 'To understand why Agrippa built at all, picture Jerusalem in the middle of the first century. It was a pilgrimage city, and the pilgrimage was enormous. Three times a year the population swelled with people coming to the Temple, and the permanent population had been rising for decades. The city had spilled out of its walls to the north, into a district Josephus calls Bezetha — the New City.' },
      { text: 'A suburb outside the walls is a suburb that cannot be defended. Agrippa\u2019s wall was meant to fix that. It was also, unmistakably, a statement: a client king with Roman backing announcing that his capital was a great city. The Romans read it the same way, which is why the emperor Claudius reportedly told him to stop.' },
      { h: 'Who lived here' },
      { text: 'The people whose houses went up over the old quarry were not grandees. This was the northern edge of town, near the gate, the sort of district where craftsmen and traders lived and worked. The ground was uneven, patched with old cuttings and sealed tomb doors, and it would have been cheap.' },
      { text: 'Archaeologically, this is the thinnest period on this whole page, and it is worth saying why. Everything built here between roughly 41 and 130 CE was either destroyed in the siege of 70 or swept away by Hadrian\u2019s engineers sixty years later. What survives is scraps in fill layers: pottery, coins, plaster, the occasional cistern. It is enough to say people lived here. It is not enough to draw their houses with confidence, which is why the blocks on this plan are shown as probable and left deliberately vague.' },
      { text: 'One more thing about this short period is worth naming plainly. It is the only stretch of the whole sequence in which the tomb was inside a living city and still visible — a sealed door in a wall at the back of somebody\u2019s yard, in a neighbourhood where people cooked and argued and hung washing. After this, it is either buried, enshrined or destroyed. It is never ordinary again.' },
      { text: 'Then, in 70 CE, the Roman army under Titus took the city and levelled most of it. Sixty years after that, after the Bar Kokhba revolt, the emperor Hadrian decided that Jerusalem should cease to exist as a Jewish city altogether, and gave orders for a Roman colony to be laid out over the ruins. The surveyors arrived with their instruments, looked at a broken hillside pitted with an old quarry, and saw a problem to be solved.' }
    ],
    debates: [
      'The line of the Third Wall is contested. Remains north of the present Old City have been claimed as Agrippa\'s wall since the 1920s and are still argued over; other scholars place it much closer to the current Ottoman wall.',
      'Whether Jerusalem\'s Christian community maintained continuous local knowledge of the tomb between 70 and 325 CE is a question of historical judgement, not archaeology. Serious historians disagree.'
    ],
    facts: [['Wall', 'Third Wall of Agrippa I'], ['Effect', 'Cemetery closed by law and custom'], ['Confidence', 'Mostly probable']]
  },

  hadrian: {
    lede: 'The Romans did not hide the tomb. They flattened a district, and the tomb happened to be under it.',
    paras: [
      { h: 'Aelia Capitolina' },
      { text: 'After crushing the Bar Kokhba revolt in 135 CE, Hadrian refounded Jerusalem as a Roman colony called Aelia Capitolina — Aelia from his own family name, Capitolina for the gods of the Capitol in Rome. Jews were barred from the city. The new town was laid out on the standard Roman grid, with a main north–south street, the Cardo Maximus, running the length of it, and public buildings arranged along it.' },
      { text: 'Roman city planners had a straightforward attitude to inconvenient ground. If the terrain did not suit the grid, they changed the terrain. This hillside, with its stepped quarry hollow, its rock faces and its old tomb doorways, was in the way of a planned civic centre. So they filled it in.' },
      { h: 'The fill that saved everything' },
      { text: 'This is the most important single fact in the archaeology of the site, and it is worth pausing on.' },
      { text: 'To build a level platform over a quarry, you dump enormous quantities of earth and broken stone into the hollow and pack it down. Where the hollow was too deep to fill economically, you throw vaults across it and build on top. The result is a flat terrace held up by massive retaining walls.' },
      { text: 'Everything under that fill stopped changing. The tomb chambers, the cut faces, the garden soil, the quarry floors with their tool marks — all of it was sealed under metres of packed rubble and left alone. Roman engineers building a forum accidentally created the best preservation conditions imaginable for the very things that later generations would come looking for. Blocks of the Hadrianic retaining wall can still be seen in the foundations of the church and in the cellar of the Russian Alexander Hospice next door, carrying the weight of everything built since.' },
      { h: 'The temple, and what we do not know about it' },
      { text: 'On the new platform, Roman Aelia got a temple. Two Christian writers tell us so. Eusebius, writing in the 330s, says that the tomb had been covered with earth and paved over, and that a shrine to Aphrodite was built above it. Jerome, later, says much the same and adds a detail — that a statue of Venus stood on the rock of the crucifixion, and one of Jupiter over the tomb.' },
      { text: 'These are the only substantial descriptions we have, and both come from Christian authors with a strong interest in the story of a pagan shrine deliberately planted on a holy place. The temple itself has never been excavated. Not one certain column, not one dedicatory inscription. What we have is fill, retaining walls, and text.' },
      { text: 'So the plan draws the podium as probable — a raised platform of some kind is required by the engineering and the topography — and the temple building itself as reconstructed, in dashed outline. Where scholars place it varies. Some put the temple squarely over the tomb, following Eusebius. Others put it over Golgotha, following Jerome, and put an open forum over the tomb instead. Others again think the "temple of Aphrodite" was a modest shrine within a much larger public square, and that Christian writers made it grander than it was because a grander insult made a better story.' },
      { h: 'A forum on the Cardo' },
      { text: 'What is not in doubt is the Cardo. The colonnaded main street of Aelia ran north–south past the eastern side of this platform, and stretches of it have been excavated and can be walked today. On the sixth-century Madaba mosaic map — a floor mosaic in a church in Jordan showing Jerusalem in remarkable detail — the Cardo runs down the middle of the city with the Holy Sepulchre complex opening off it, steps and all.' },
      { text: 'A forum, or at least a large paved public space, occupied the ground between the temple platform and the street. This is normal Roman planning: the civic heart of a colony sits where the main street can feed it.' },
      { h: 'How you build a platform over a hole' },
      { text: 'The engineering deserves a moment, because it is the reason this site exists in the form it does.' },
      { text: 'A Roman surveyor faced with this ground had two problems. The hollow was deep and irregular, and the natural slope ran away downhill to the east. Filling the whole thing solid would have taken an extraordinary volume of material carted uphill through a city. So the engineers did what Roman engineers always did: they mixed methods. Where the hollow was shallow, they packed it with earth and rubble and rammed it down in layers. Where it was deepest, on the western side, they threw vaults across the gap and built on top of those, leaving voids underneath.' },
      { text: 'Around the edge they built a retaining wall of very large squared blocks to hold the whole mass in place. That wall is the most solidly attested Hadrianic feature on the site. Parts of it are visible today in the cellar of the Russian Alexander Hospice next door, and its blocks were reused as the footing of everything built afterwards, including the church.' },
      { h: 'The Madaba map' },
      { text: 'One piece of evidence deserves special mention, because it is unlike everything else. In a church in Madaba, in Jordan, there is a floor mosaic of the sixth century showing a map of the Holy Land. At its centre is Jerusalem, drawn in bird\u2019s-eye view with real streets and real buildings.' },
      { text: 'The Cardo runs down the middle with its two rows of columns clearly shown, and opening off it, unmistakably, is the Holy Sepulchre complex: steps up from the street, a gate, a basilica roof, a courtyard, and a dome at the western end. It is the earliest picture of this site that we have, made by someone who could walk there. It confirms the arrangement of street, steps and buildings that the excavated fragments imply, and it is the main reason the propylaeum can be drawn at all.' },
      { h: 'Nearly two centuries of silence' },
      { text: 'For about 190 years, that is what stood here. Pavement, columns, a temple platform, the ordinary noise of a small provincial Roman city. Beneath it, undisturbed and unvisited, lay the quarry, the garden soil, the tombs, and the rock of Golgotha buried nearly to its top.' },
      { text: 'And then in 325 CE a Roman emperor became a Christian, a bishop of Jerusalem asked him for something, and men with picks were sent to take the platform apart.' }
    ],
    debates: [
      'Temple or forum over the tomb? Eusebius implies a temple directly above it; Jerome puts Venus on Golgotha. The plan shows the temple over the tomb but flags the position as disputed.',
      'The dedication is uncertain — Aphrodite/Venus in the Christian sources, but a colony called Capitolina would be expected to honour the Capitoline triad. Some scholars think the sources have simplified a larger complex.',
      'No element of the temple superstructure has ever been excavated. Everything above podium level is drawn from texts.'
    ],
    facts: [['Founded', '135 CE'], ['Key evidence', 'Retaining walls, fill, Cardo'], ['Temple', 'Never excavated']]
  },

  constantine: {
    lede: 'Constantine did not build a church here. He built three buildings in a row, and made you walk through all of them.',
    paras: [
      { h: 'Digging for a tomb' },
      { text: 'In 325 CE the bishops of the empire met at Nicaea, and Macarius, bishop of Jerusalem, seems to have used the occasion to put a request to the emperor. Whatever was said, Constantine ordered the Roman platform in Aelia demolished and the ground beneath it cleared.' },
      { text: 'Eusebius, who was there in the sense of being a bishop in the same province and writing within a decade, describes the demolition: the shrine pulled down, the paving lifted, the earth carted away to a distance because it was thought polluted. And then, he says, against all expectation, the tomb appeared.' },
      { text: 'We should read that carefully. Eusebius is writing propaganda in the honest, ancient sense — a celebration of an emperor. He is not writing an excavation report. But the physical situation he describes is exactly what the archaeology now shows: a rock-cut tomb sealed under Hadrianic fill. Whatever the workmen expected to find, a tomb is what was there to be found.' },
      { h: 'Three buildings, one journey' },
      { text: 'What Constantine\'s architects built between about 326 and 335 was not a single church but a sequence, laid out along a straight line running west from the Cardo. A pilgrim experienced it as a journey inward.' },
      { text: 'First, from the busy colonnaded street, a monumental stair and triple gateway: the propylaeum. You climbed out of the traffic of the city.' },
      { text: 'Through the gate, an atrium — an open courtyard with porticoes, where the noise dropped away.' },
      { text: 'Then the Martyrium: a huge basilica, five aisles wide, roughly 46 metres by 40, with a gilded coffered ceiling and marble on the walls. Its apse was at the western end, facing you as you came in, ringed by twelve columns that Eusebius says carried great silver bowls. This was the church for the liturgy, big enough for a city.' },
      { text: 'Out through its western door into a second open courtyard, the Triportico, porticoed on three sides. In its south-east corner, standing free in the open air, was the rock of Golgotha — the flawed pinnacle the quarrymen had left behind, now trimmed square, its base cut back, with a jewelled cross set on top of it. Pilgrims in the 380s describe it plainly, and the Spanish traveller Egeria describes the services held in front of it.' },
      { text: 'And finally, at the western end of everything, the Anastasis — the Resurrection — a great round building enclosing the tomb.' },
      { h: 'The Edicule: a tomb turned inside out' },
      { text: 'The tomb chamber had been cut into a hillside. A chamber inside a hill cannot be walked around, cannot be seen from all sides, cannot be the centre of a circular building. So Constantine\'s masons did something audacious: they cut the hillside away from it. They quarried back the rock on every side until the tomb chamber stood alone, an isolated block of living stone with the burial shelf inside it, and then they dressed that block with columns and a conical roof.' },
      { text: 'The result is called the Edicule, from the Latin for a little house. It is the most extraordinary object in the whole history of this site: not a building over a tomb but a tomb carved out of its own hill and turned into a building. We know its appearance only indirectly — from written descriptions, from pilgrim sketches, and from small metal souvenir flasks made for travellers, which show a domed canopy on columns with a screen across the door.' },
      { h: 'The rotunda' },
      { text: 'Around the Edicule rose the rotunda: a ring of twelve columns and four pier groups, roughly 21 metres across inside, carrying a dome, with an ambulatory circling the whole thing so that pilgrims could walk around the tomb.' },
      { text: 'The lower courses of that outer wall are still standing. Not reconstructed, not restored — standing. You can put your hand on fourth-century masonry in the church today. This is one of the reasons the site is taken seriously even by sceptics: whatever you conclude about the identification, the Constantinian building is physically here.' },
      { text: 'The rotunda was probably not finished with the basilica. The Martyrium was dedicated in September 335, with the empire\'s bishops in attendance, and the evidence suggests the round building was completed over the following decades, into the 380s. Building a dome takes longer than building a hall.' },
      { h: 'What it felt like' },
      { text: 'We are unusually lucky in having a pilgrim who wrote things down. Egeria, a woman from somewhere in the western empire — probably Spain or Gaul — travelled to Jerusalem in the early 380s and sent home a long, chatty letter describing the services she attended.' },
      { text: 'She is not interested in architecture; she is interested in what happened. She describes the church lit with lamps before dawn, hymns sung in Greek and translated on the spot into Syriac for the local congregation, the bishop reading the resurrection story standing at the tomb itself, and crowds large enough that the singing echoed off the rock. On Good Friday she describes the wood of the cross brought out on a table and guarded by deacons, because on one occasion somebody had bitten off a piece to steal it.' },
      { text: 'It is the small human details that make the plan on the left come alive. These were not diagrams. They were buildings full of tired, moved, occasionally badly behaved people, and Egeria heard the noise they made.' },
      { text: 'One more thing about the design. Every earlier Roman temple made you approach a building and stop outside it, because the god lived within and you did not. Constantine\u2019s architects inverted that. They took a rock-cut hole in a hillside, turned it inside out until it stood free in the middle of a round room, and then built a route that pulled you through gate, court, hall and courtyard until you arrived at it. The whole complex is a machine for walking towards something and being allowed in.' },
      { h: 'What is solid, and what is drawn from words' },
      { text: 'On this plan the rotunda foundations and lower wall are secure. The basilica footprint is probable: parts of its walls and apse survive under later buildings and were recorded by excavators in the twentieth century, but much of the plan is projection from those fragments. The atrium and propylaeum are reconstructed — supported by the Madaba map and by texts, but not excavated in full. The Edicule is reconstructed, entirely: nothing of Constantine\'s casing survives, only the rock inside it.' }
    ],
    debates: [
      'The exact plan of the Martyrium — five aisles or three, the form of the western apse, the position of the atrium colonnades — rests on limited excavation and is reconstructed differently by different scholars.',
      'Whether the rotunda was part of the original design or a later addition of the 340s–380s is debated. The masonry joins can be read either way.',
      'The appearance of the Constantinian Edicule is known only from texts, pilgrim flasks and the small Narbonne model. All published reconstructions differ.'
    ],
    facts: [['Basilica dedicated', 'September 335'], ['Rotunda', 'Lower walls standing'], ['Edicule', 'Rock cut free from hillside']]
  },

  modestus: {
    lede: 'In 614 a Persian army took Jerusalem, and the church burned. What happened next is harder to see than the sources suggest.',
    paras: [
      { h: 'The war' },
      { text: 'The early seventh century brought the last and most exhausting war between the two great powers of the ancient world, the Roman (Byzantine) empire and Sasanian Persia. In 614 a Persian army took Jerusalem after a short siege. The city was sacked, a large number of people were killed or deported, and the relic of the True Cross was carried away to Persia.' },
      { text: 'The Christian sources describing the sack are vivid and horrified, and they are also written by people with reasons to make the disaster total: a catastrophe explains a defeat, justifies a reconquest, and casts blame. One account lists tens of thousands of dead. Modern historians treat these numbers with caution, and the archaeological signs of a general destruction across Jerusalem in 614 are patchier than the texts would lead you to expect.' },
      { h: 'Fire, not collapse' },
      { text: 'For the Holy Sepulchre specifically, the evidence points to burning rather than demolition. Timber roofs, screens, furnishings and hangings would have gone up readily; stone walls do not. Fire-cracked and scorched blocks of fourth-century masonry have been recorded inside the building, which is consistent with a serious fire in a standing structure.' },
      { text: 'This is why the plan for this period shows the same footprint as before, with the roofed areas marked as burned and the walls still standing. It is not that nothing happened. It is that what happened was a fire in a building, and the building survived it.' },
      { h: 'Modestus' },
      { text: 'The repairs were organised by Modestus, abbot of the monastery of St Theodosius and acting head of the Jerusalem church while the patriarch Zacharias was a prisoner in Persia. He worked fast and, by all accounts, on a tight budget, with help sent from the churches of Egypt and from Christian communities across the region.' },
      { text: 'Contemporary and near-contemporary writers give him credit for restoring the Anastasis, the Martyrium, Golgotha and the church of the Finding of the Cross. What they describe sounds like emergency work rather than reconstruction: new timber roofs, plain masonry where marble had been, columns re-erected from salvaged shafts. The seventh-century pilgrim Arculf, who visited a few decades later and whose account survives because a Scottish abbot wrote it down, describes a working complex of buildings — not a ruin, but not the gleaming fourth-century original either.' },
      { text: 'The chapels Modestus is said to have added — to the Virgin, to St John, to the Trinity — are shown on the plan in dashed outline at the south-east. Their existence is reasonably well attested. Their positions are frankly guesswork, placed here by analogy with later arrangements.' },
      { h: 'The Cross comes back, briefly' },
      { text: 'In 630 the emperor Heraclius, having beaten the Persians, returned the True Cross to Jerusalem in a ceremony that became one of the great set-pieces of Byzantine memory: the emperor carrying the relic up to the church, reportedly on foot and barefoot. It was a moment of restoration, celebrated as the end of the crisis.' },
      { text: 'It lasted eight years. In 638, Jerusalem surrendered to the armies of the Rashidun Caliphate, and a new period began — one that, contrary to a widespread assumption, would leave this church standing for the better part of four centuries.' },
      { h: 'Reading damage in a living building' },
      { text: 'A word about method. It is genuinely hard to date destruction in a building that has been continuously used, repaired, refaced and rebuilt for seventeen hundred years. A scorched block can be reused from somewhere else. A crack can come from an earthquake — and Jerusalem has had many — rather than from a war. A change in masonry style tells you there was a rebuilding but not always which one.' },
      { text: 'That is why the confidence markers on this period\'s plan are mostly "probable" rather than "secure". The 614 fire almost certainly happened and almost certainly damaged this church badly. Exactly which stones record it is another matter.' },
      { h: 'Why the sources are hard to use' },
      { text: 'The main account of the sack comes from a monk called Strategios, and it survives in Georgian and Arabic translation rather than in the original. He describes the city taken, churches burned and a great many people killed, and gives figures modern historians consider impossibly high. He writes as a survivor and a partisan, in a genre where catastrophe is expected.' },
      { text: 'None of this means he is lying. It means his account is testimony, not measurement. Archaeology has found burnt layers in Jerusalem from this period, but not the uniform city-wide destruction horizon the texts imply. The likeliest reading is that something genuinely terrible happened, concentrated on particular buildings and particular days, and that the retelling flattened it into total ruin.' },
      { h: 'Rebuilding without money' },
      { text: 'Modestus\u2019s repairs tell their own story about conditions. A church rebuilt in a hurry looks a certain way: salvaged columns of different heights, stones set on plain footings, timber where vaulting had been, plaster where marble had been. Later visitors noticed the difference.' },
      { text: 'He was working in an occupied province with the patriarch a prisoner, and much of the money and material came as charity from elsewhere — Egypt in particular, and Christian communities across Syria and Mesopotamia. The Jerusalem church of the 620s was not the confident imperial institution of Constantine\u2019s day. It was a battered organisation keeping the doors open.' },
      { text: 'And the doors did stay open. That is the thing worth holding on to across this whole period. Through the war, the sack, the deportations and the change of government that followed, pilgrims kept arriving and services kept being sung. The building changed hands and changed appearance. What it was for did not change.' },
      { text: 'It is worth noticing what this period does to the plan on the left. Almost nothing moves. The walls stand where they stood, the courtyard is the same courtyard, the tomb is untouched. What changes is the quality of everything: cheaper materials, plainer surfaces, salvaged parts. Buildings record hard times in their finish long before they record them in their shape.' },
      { text: 'There is a broader lesson in this period about reading ruins. We tend to imagine destruction as a single dramatic moment that leaves a clean line in the ground. Real damage to real buildings is messier: a fire here, a patch there, a column reused from somewhere else, a roof replaced twice in a decade. The seventh century on this site is a hundred small repairs, and the sources give us one loud year.' },
    ],
    debates: [
      'The scale of the 614 destruction is disputed. Textual accounts describe near-total ruin; archaeology across Jerusalem suggests something more limited and localised.',
      'Which surviving fire damage belongs to 614 and which to the 1808 fire or to earthquakes cannot always be distinguished.',
      'The location and even the number of Modestus\'s added chapels are unknown; the plan shows one probable grouping among several proposed.'
    ],
    facts: [['Sack', '614 CE'], ['Repairs', 'c. 616–626, under Modestus'], ['Damage type', 'Fire, walls standing']]
  }
};
export default A;
