// Period essays, part 2 (periods 07-11).
const B = {
  hakim: {
    lede: 'For most of four hundred years under Muslim rule the church stood, worked and received pilgrims. Then one ruler gave one order.',
    paras: [
      { h: 'A church under a new government' },
      { text: 'When Jerusalem surrendered in 638, the church was not destroyed. Under the Rashidun, Umayyad, Abbasid and Fatimid governments that followed, Christians in Jerusalem paid a tax, lived under restrictions that tightened and loosened with the politics of the day, and kept their churches. Pilgrims kept arriving — from Byzantium, from Armenia, from Georgia, and increasingly from western Europe.' },
      { text: 'The Dome of the Rock was built in 691 on the Temple Mount, a short walk away, and the two great buildings stood in the same skyline for centuries. There were bad years: the church was damaged in disturbances in 841, 938 and 966, when the doors and parts of the roof were burned. Each time it was patched up.' },
      { text: 'This is the part of the story that most popular accounts skip, and it deserves emphasis. Four centuries is longer than the United States has existed. For most of that time the building on this site was a functioning, maintained, visited church.' },
      { h: '1009' },
      { text: 'Al-Hakim bi-Amr Allah was the sixth Fatimid caliph, ruling from Cairo. His reign is one of the strangest in medieval history — a series of sweeping, contradictory decrees, some of them directed at Christians and Jews, some at his own officials, some at apparently trivial matters of daily life. Historians have argued for a thousand years about what drove him.' },
      { text: 'In 1009 he ordered the Church of the Holy Sepulchre destroyed. The order was carried out with unusual thoroughness. The Martyrium basilica — Constantine\'s great five-aisled hall — was levelled to its foundations and never rebuilt. The rotunda was pulled down as far as the demolition crews could manage. And, according to the sources, particular effort was directed at the tomb itself: workmen were set to hack the rock apart with picks so that nothing of it would remain.' },
      { text: 'The event is recorded by Christian, Muslim and Jewish chroniclers alike, which is unusual and makes it about as securely attested as any medieval event can be. Its consequences reached a long way; western European reactions to the news of the destruction are part of the background to the Crusades, ninety years later.' },
      { h: 'Why anything survived at all' },
      { text: 'Demolition is harder work than it sounds. The lower courses of the rotunda wall were built of very large stones, thick and well bedded, and taking them apart by hand with the tools of the day was an enormous labour for no obvious gain. The crews got the wall down to roughly eleven metres and stopped.' },
      { text: 'That is why fourth-century masonry is still standing today. It survived not because it was spared but because it was too much trouble.' },
      { text: 'The tomb fared much worse. Everything that had been left of the rock chamber after Constantine\'s masons cut it free — the walls, the roof, the doorway — was broken up. What survived was the burial shelf itself and the stub of rock beneath it, at floor level, where the picks could not easily get purchase and where debris quickly piled up.' },
      { h: 'What the 2016 restoration showed' },
      { text: 'In October 2016, during the structural restoration of the Edicule, the marble slab covering the burial shelf was lifted for the first time in centuries. Beneath it the team from the National Technical University of Athens found fill material, a broken older marble slab with a cross incised on it, and then the original limestone shelf.' },
      { text: 'Mortar taken from between the shelf and the marble covering was dated by a laboratory method called optically stimulated luminescence — which measures the last time buried mineral grains saw daylight — and returned a date in the middle of the fourth century. In other words, the covering appears to have been placed in the Constantinian period, and the shelf beneath it is genuinely the rock that was enclosed then.' },
      { text: 'That does not tell you who was buried there. It does tell you that the rock inside the 1810 Edicule is not a later invention, and that it survived al-Hakim.' },
      { h: 'Ruins on a platform' },
      { text: 'For about thirty years after 1009 the site was a wreck: a broken drum of wall around a heap of debris, the courtyard buried, the basilica reduced to foundations under a spread of rubble that would soon have houses on it. Pilgrims still came, and prayed in the ruins.' },
      { text: 'Then the politics shifted. The Fatimid government and the Byzantine empire began, slowly and with much haggling, to negotiate.' },
      { h: 'The four quiet centuries, in more detail' },
      { text: 'It is worth filling in what those centuries actually looked like, because "quiet" is doing a lot of work in that sentence.' },
      { text: 'Christians under early Islamic rule were a protected community. They paid a poll tax, were barred from some public displays, and lived under rules about building and repair that were enforced strictly or loosely depending on who was governing. Within those limits the church functioned: it had a patriarch, clergy, property, and a steady stream of visitors.' },
      { text: 'Pilgrim accounts survive from across the period, and they are a strange and wonderful genre — part travelogue, part shopping list of relics, part complaint about the roads. The bishop Arculf in the 680s, the monk Bernard in the 860s, and a run of Georgian and Armenian visitors all describe a working complex of buildings on this site.' },
      { text: 'There were bad years too, and they follow a pattern: disturbance in the city, damage to the church, repair afterwards. Fires in 841, 938 and 966 burned doors and roofs. Each time the building was patched and reopened. Nothing before 1009 was final.' },
      { h: 'Why 1009 was different' },
      { text: 'Al-Hakim\u2019s order was not a riot. It was a decree, carried out by officials, with the stated intention that the site should stop being a place of pilgrimage. That is why the work went beyond burning: the basilica was taken down to its foundations, and men were set to break the rock of the tomb itself with picks — an enormous deliberate labour that only makes sense as an attempt to erase one specific object rather than damage a building.' },
      { text: 'And it very nearly worked. Had the rotunda walls been a little thinner, or the tomb rock a little more accessible to a pick, there would be nothing physical left to argue about and this page would end here.' },
    ],
    debates: [
      'Al-Hakim\'s motives are debated: religious zeal, political calculation, and mental illness have all been argued, and none is provable.',
      'How much of the rotunda was destroyed is uncertain; estimates of surviving height range from about 8 to 11 m.',
      'The 2016 mortar dates are accepted by most specialists but rest on a small number of samples from a context that has been disturbed many times.'
    ],
    facts: [['Destroyed', '1009 CE'], ['Basilica', 'Never rebuilt'], ['Tomb shelf', 'Survived; 4th-c. mortar dated 2016']]
  },

  monomachos: {
    lede: 'The church that rose in the 1040s was smaller, poorer and stranger than the one it replaced — and its shape still governs the building today.',
    paras: [
      { h: 'Diplomacy first' },
      { text: 'Rebuilding required permission from Cairo, and permission took decades. A series of treaties between the Fatimid caliphate and the Byzantine empire eventually included the right to restore the church, in exchange for concessions elsewhere: trade terms, the release of prisoners, the right to name the ruler in the Friday prayers in Constantinople\'s mosque. The emperor Constantine IX Monomachos funded the work, which ran roughly from 1042 to 1048.' },
      { text: 'The money was real but limited, and the ambition was correspondingly modest. Nobody was going to rebuild a five-aisled imperial basilica in an occupied provincial city.' },
      { h: 'What was rebuilt, and what was not' },
      { text: 'The rotunda was restored. Its surviving fourth-century courses were built up again, and above them the eleventh-century work is visible to this day as a change in the masonry — one of the clearest archaeological joins in the building. A gallery was added at upper level, so that more people could see the tomb from above, and the whole was covered with a new dome.' },
      { text: 'The Edicule was rebuilt too, but now as masonry rather than living rock. The shattered remains of the tomb chamber were enclosed in a built structure. From this point on, everything the pilgrim sees is a container: the rock itself is inside, hidden.' },
      { text: 'The Martyrium was not rebuilt. Its site — a rectangle of ground the size of a cathedral — was left open, then gradually built over with houses, and it has stayed built over ever since. If you stand in the streets east of the church today, you are walking on Constantine\'s basilica.' },
      { h: 'The apse that changed everything' },
      { text: 'With no basilica, there was nowhere to hold the main liturgy. A rotunda is a shrine, not a congregational church; it has a monument in the middle and no place for an altar.' },
      { text: 'The solution was to cut a large apse through the eastern side of the rotunda wall, facing the old courtyard, and put the altar there. It sounds like a technicality. It was in fact the decisive move in the architectural history of the site, because it turned the rotunda from a free-standing round shrine into the western end of a church that faced east. Every later rebuilding — Crusader, Ottoman, modern — accepted that orientation. The plan you walk through today is the descendant of an emergency fix made in the 1040s.' },
      { text: 'Chapels were added around the ambulatory, and a small chapel was built over the rock of Golgotha at the south-east corner of the courtyard, which was now an open yard between the rotunda and the houses beyond.' },
      { h: 'How we know' },
      { text: 'This period is unusually well documented for the Middle Ages. Several pilgrims describe the church between 1050 and 1099 — the Russian abbot Daniel is the most detailed — and their accounts broadly agree with each other and with the masonry evidence. The eleventh-century building work can be identified in the fabric, and the join between fourth- and eleventh-century courses has been recorded in survey drawings.' },
      { text: 'The eastern apse itself was later demolished by the Crusaders when they built through it, so its exact form is reconstructed rather than observed. The plan shows it as probable, drawn from the descriptions and from the traces in the wall.' },
      { h: 'A church in a divided city' },
      { text: 'Something else began in this period that has never ended. The rebuilt church was Byzantine, but Jerusalem\'s Christians were not one community: Greeks, Armenians, Syriacs, Georgians, Copts and Ethiopians all had claims, clergy and chapels here, and the arrangements between them were made and remade by negotiation, custom and occasional force.' },
      { text: 'The habit of dividing this building between communities, chapel by chapel and hour by hour, starts long before the Status Quo was written down in the nineteenth century. It starts here, in a half-rebuilt church with more claimants than space.' },
      { h: 'What a pilgrim saw in 1100' },
      { text: 'The Russian abbot Daniel came here early in the twelfth century and left the most detailed description we have of the Monomachos church. He is a good witness because he is practical: he counts columns, measures in paces, and says which door you go in by.' },
      { text: 'He describes a round church with an open eye at the top of the dome, galleries above the ambulatory, and the tomb standing under the opening. He notes the small chapel over Golgotha across the courtyard, the stair down to the place where the cross was found, and the various communities with their own altars. Read alongside the masonry, his account is what allows the plan on the left to be drawn at all.' },
      { h: 'The open dome' },
      { text: 'That opening at the top of the dome is worth pausing on. The rotunda\u2019s dome had an oculus — a circular hole — directly above the Edicule, so that daylight fell on the tomb. So did rain. Pilgrims mention water on the floor.' },
      { text: 'It was almost certainly not a whim. A dome with a hole in it is lighter, cheaper and less structurally demanding than a closed one, which matters when you are rebuilding on damaged walls with limited money. But the effect — a shaft of light dropping onto the tomb out of the open sky — was so striking that every later rebuilding kept the idea. The present dome still has an opening at its crown, glazed now, with a gilded starburst around it.' },
      { text: 'Sometimes an accident of engineering becomes the defining image of a building.' },
      { text: 'Step back and look at what the eleventh century leaves behind. A rotunda restored on fourth-century footings, an altar improvised into its eastern wall, a masonry box where a rock-cut tomb had been, and a great empty rectangle to the east where the largest church in the city used to stand. It is a diminished site, and an honest one. Everything built here afterwards is built on that compromise.' },
      { text: 'It is also the moment the site stops trying to be what it was. Nobody after 1048 attempts to rebuild Constantine\u2019s complex. The Crusaders, the Ottomans and the modern restorers all work with the smaller footprint the eleventh century left them, and the great basilica passes out of memory so completely that for centuries nobody was sure where it had stood.' },
    ],
    debates: [
      'The form of the eastern apse is reconstructed from pilgrim descriptions; it was destroyed by the Crusader rebuilding and no plan of it survives.',
      'Some scholars argue that significant rebuilding began before 1042 under earlier, local initiatives, and that Monomachos\'s contribution has been overstated in the Byzantine sources.',
      'The extent of the eleventh-century gallery — continuous, or only over part of the ambulatory — is not agreed.'
    ],
    facts: [['Rebuilt', '1042–1048'], ['Funded by', 'Constantine IX Monomachos'], ['Martyrium', 'Abandoned']]
  },

  crusader: {
    lede: 'The Crusaders found a shrine, a yard and a scatter of chapels, and put a single roof over the lot. That roof is the church you walk into today.',
    paras: [
      { h: 'A church made of separate pieces' },
      { text: 'When the armies of the First Crusade took Jerusalem in 1099, they inherited an awkward arrangement. There was the rotunda, restored fifty years earlier, with its makeshift eastern apse. There was an open courtyard east of it. In the courtyard\'s south-east corner was the small chapel over Golgotha. Round about were the chapels of half a dozen communities, a stair down to the place where the True Cross was said to have been found, and a great deal of accumulated building.' },
      { text: 'To get from the tomb to Calvary you went outside and crossed a yard. The holiest sites in Latin Christendom were a set of separate destinations, and the pilgrim traffic was becoming unmanageable.' },
      { h: 'The Crusader solution' },
      { text: 'The Latin church spent the first half of the twelfth century solving this, and the solution was simple in concept and enormous in execution: roof the courtyard. Build a proper church in the space between the rotunda and the eastern buildings, join it to the rotunda through the eleventh-century apse, and bring Calvary inside the new building\'s south-east corner.' },
      { text: 'What they built is French Romanesque, and it would look at home in Burgundy. A transept running north–south, a choir east of the crossing, and around the choir an ambulatory — a curving aisle that lets pilgrims walk behind the high altar without disturbing the service — with three chapels radiating from it. Groin vaults, heavy piers, round arches, and carved capitals.' },
      { text: 'This is the single most important structural fact about the modern church. Almost every wall you touch above floor level in the eastern half of the building is Crusader work of the 1130s and 1140s.' },
      { h: 'The south front' },
      { text: 'The old entrance from the east, up from the Cardo through Constantine\'s propylaeum, had been gone since 1009 and its site was covered in houses. So the Crusaders made a new front on the south side, opening onto a courtyard — the parvis — reached from the streets of the Christian quarter.' },
      { text: 'The south facade is a set piece: two round-arched portals side by side, with two arched windows above them, carved lintels, and marble columns. Next to it rises the bell tower, finished around 1170. The design is deliberately public and deliberately Latin, announcing the Kingdom of Jerusalem in stone.' },
      { text: 'The eastern of the two doors was walled up centuries later and remains blocked. Every one of the millions of visitors who enters the church each year goes through the western door of a twelfth-century facade.' },
      { h: 'Calvary indoors' },
      { text: 'The rock of Golgotha was enclosed in a two-storey arrangement at the south-east corner of the new church: a chapel at ground level and, above it, at the level of the rock\'s summit, the Calvary chapel reached by a steep stair from inside the church. That is still how it works. The stair is still steep.' },
      { text: 'Below and east, a long flight of steps runs down to the Chapel of St Helena and, below that, to the chapel of the Finding of the Cross — which is, in plain archaeological terms, a room in the ancient quarry. The walls there are cut rock faces. On one of them is a drawing of a ship with a Latin inscription, scratched by some early pilgrim, one of the small human marks that survive from a period we know almost nothing about.' },
      { h: '15 July 1149' },
      { text: 'The church was rededicated on 15 July 1149 — chosen to fall exactly fifty years after the Crusader capture of the city. It was not finished; work continued for decades. But from that date the site had, for the first time in its history, one building.' },
      { text: 'The Crusader kingdom lost Jerusalem to Saladin in 1187, less than forty years later. The church was not destroyed. It was taken over, taxed, and kept open for Christian pilgrimage under Muslim rule, and the keys to its door were entrusted to a local Muslim family — an arrangement that, remarkably, still operates.' },
      { h: 'The building as a machine for pilgrims' },
      { text: 'It is easy to read the Crusader plan as architecture. It is more useful to read it as crowd management.' },
      { text: 'By the twelfth century the traffic through this building was immense, and it was seasonal — enormous at Easter, heavy through the summer sailing season, thin in winter. A church that has to move thousands of people past a few fixed points needs circulation, and that is exactly what an ambulatory with radiating chapels provides. You come in the south door, go up to Calvary by one stair and down by another, circle behind the high altar without crossing the service, and reach the tomb.' },
      { text: 'The three radiating chapels — St Longinus, the Division of the Robes, the Mocking — each mark an episode of the passion story. Walking the ambulatory is walking the narrative. The design is doing catechism as well as traffic control.' },
      { h: 'The masons' },
      { text: 'The carving on the south facade and inside the church is high-quality French Romanesque work, which raises an interesting question: who cut it?' },
      { text: 'Some of the craftsmen were certainly westerners who came out with, or after, the armies. But the Latin Kingdom was a small ruling class in a populous country, and the workforce on any large building site would have been local — Syrian Christian, Armenian, Muslim. Art historians have identified hands in the sculpture that look trained in France and others trained in the eastern Mediterranean, sometimes on the same doorway.' },
      { text: 'The building is a hybrid, made by mixed crews, in a kingdom that was itself a strange graft. That is visible in the stone if you know to look.' },
      { text: 'And this is the period that settles the shape of the place for good. Every later event on this page — the fire, the Ottoman rebuilding, the Status Quo, the modern restorations — happens inside the walls the Crusaders raised. They did not add the most famous parts of the site. They added the container that holds all of them at once.' },
    ],
    debates: [
      'The exact sequence and dating of the Crusader campaigns is debated; the 1149 dedication marks a stage, not a completion.',
      'How much eleventh-century fabric was retained inside the new choir walls is hard to establish without invasive survey.',
      'The original design of the south facade\'s upper stage and the roofline above it is partly reconstructed from later drawings.'
    ],
    facts: [['Rededicated', '15 July 1149'], ['Style', 'French Romanesque'], ['Status', 'Largely standing']]
  },

  komnenos: {
    lede: 'On the night of 11 October 1808 the rotunda caught fire, and the argument over who would rebuild it went all the way to imperial capitals.',
    paras: [
      { h: 'Six centuries of wear' },
      { text: 'Between 1187 and 1808 the church was repaired, patched, propped and quarrelled over, but not fundamentally rebuilt. Earthquakes shook it — the tremor of 1545 brought down part of the bell tower, which was afterwards cut down to the stump you see today. The Ottoman authorities, who ruled Jerusalem from 1517, regulated access and adjudicated disputes between the Christian communities, generally in favour of whoever had most recently paid.' },
      { text: 'The building filled up with structures: chapels, screens, cupboards, staircases, oil lamps, hangings and stored timber. It was crowded and it was flammable.' },
      { h: 'The fire' },
      { text: 'The fire of 1808 started in the Armenian gallery of the rotunda, in the small hours. Timber galleries, screens and the conical roof burned. The heat cracked the marble facing off the Edicule, brought down the dome, and split the medieval columns of the rotunda. The Crusader church to the east, being stone-vaulted, came through comparatively well; the rotunda was gutted.' },
      { h: 'Who gets to rebuild' },
      { text: 'In a building shared by rival communities under an imperial government, the right to carry out repairs is not a technical matter. It is a claim of ownership. Whoever rebuilds a chapel has, in effect, established a right to it.' },
      { text: 'So the negotiations after 1808 were fierce, conducted through the Ottoman court and with pressure applied from Russia, France and Austria on behalf of their favoured communities. The Greek Orthodox Patriarchate won the main commission. Their architect was Nikolaos Komnenos of Mytilene.' },
      { h: 'What Komnenos did' },
      { text: 'Komnenos worked fast, and he worked in the Ottoman baroque taste of his own day rather than in imitation of what had burned. Three of his decisions shaped the church we have.' },
      { text: 'First, the rotunda piers. The medieval columns were cracked and unsafe, so he encased and thickened them into heavy masonry piers. The rotunda\'s interior became stouter, darker and less elegant than the one it replaced — a change that later architects and art historians have complained about ever since.' },
      { text: 'Second, the Edicule. He demolished what remained of the fire-damaged structure and built a new one: a rectangular chapel of pink-cream limestone with pilasters, a little domed cupola over the western end, and a low door forcing every visitor to stoop. It is not to everyone\'s taste, and it is the Edicule that stands today. Inside it, on the same alignment as always, is the burial shelf.' },
      { text: 'Third — and most consequential for how the building feels — he walled off the Crusader choir. Where the twelfth-century church had been one continuous space from the rotunda to the ambulatory, Komnenos enclosed the choir with solid walls and an iconostasis, turning it into a separate Greek Orthodox church, the Katholikon. The result is that the modern visitor experiences not one great interior but a warren of rooms, and the axial view from the tomb to the eastern apse — the whole point of the Crusader plan — is gone.' },
      { h: 'A building held together by treaty' },
      { text: 'The rebuilding settled the physical fabric but not the disputes. Quarrels over rights within the church rumbled on through the nineteenth century, contributing directly to the diplomatic crisis over the holy places that helped trigger the Crimean War in the 1850s.' },
      { text: 'The result was the Status Quo: an Ottoman decree of 1852, later confirmed by international agreement, freezing every arrangement in the church exactly as it then stood. Which community owns which chapel, who may sweep which step, at what hour each liturgy may be sung, who holds the keys — all fixed, permanently. Any change requires the agreement of all parties, which is why a wooden ladder leaning against a window ledge on the facade, recorded there since at least the eighteenth century, has never been moved.' },
      { h: 'The keys' },
      { text: 'One arrangement from this long Ottoman stretch deserves telling on its own, because it is the oldest working piece of the church\u2019s constitution.' },
      { text: 'The door of the Holy Sepulchre is opened and closed each day by members of two Muslim families of Jerusalem — one family holds the key, the other performs the opening. The arrangement is traditionally traced back to the twelfth century and has run in its present form for centuries.' },
      { text: 'The logic is simple and rather elegant. If any one Christian community held the key, that community would control access, and access is power. Giving the key to a neutral party removes the question. Every morning a man arrives with a heavy iron key, a ladder is passed out through a hatch in the door, and the church is opened by someone with no stake in the arguments inside.' },
      { h: 'Why the church looks the way it does' },
      { text: 'Visitors are often surprised by the interior. They expect a cathedral and find something closer to a stacked warren: dim, subdivided, crowded with lamps and screens and competing decorative schemes, with staircases appearing in unexpected corners.' },
      { text: 'That is not neglect or bad taste. It is the physical record of the settlement described above. Each community decorated, maintained and rebuilt only what was indisputably its own, in its own style and at its own moment, and the boundaries are visible in the change from Greek to Latin to Armenian ornament as you walk. Komnenos\u2019s walls made those divisions structural.' },
      { text: 'You are not looking at a single design. You are looking at a treaty rendered in stone, plaster, silver lamps and paint.' },
      { text: 'It is easy to be sniffy about the nineteenth century here. But Komnenos was rebuilding a burnt-out shrine under a foreign government, for clients who did not trust each other, on a deadline set by politics. That the building stood, and kept standing through the earthquakes and the neglect that followed, is not nothing.' },
      { text: 'And the Edicule he built is now itself a historic object. When engineers restored it in 2016 they were conserving Komnenos\u2019s work, not replacing it — the pink-and-cream shell that generations of visitors found gaudy has become, simply by lasting, part of what the site is.' },
      { text: 'That is the pattern of this whole site, if you follow it from the top of this page to the bottom. Nothing here was designed as a monument. A quarryman left a bad rock. A family cut a tomb in a cheap patch of ground. A Roman engineer filled a hole. A Greek builder threw up a shell after a fire. Every layer was somebody solving an immediate problem, and every layer became sacred to the people who came next.' },
    ],
    debates: [
      'The extent of Komnenos\'s intervention in the rotunda wall above gallery level is not fully published; how much medieval fabric he removed is uncertain.',
      'Whether the walling-off of the Katholikon was structurally necessary or purely a matter of jurisdiction is still argued.',
      'Reconstructions of the pre-1808 Edicule rely on drawings and prints of varying reliability, which disagree in detail.'
    ],
    facts: [['Fire', '11 October 1808'], ['Architect', 'Nikolaos Komnenos'], ['Edicule', 'Built 1810; standing']]
  },

  today: {
    lede: 'A building that cannot be altered has, in the last decade, been quietly opened up — first the tomb, then the floor.',
    paras: [
      { h: 'Frozen' },
      { text: 'The Church of the Holy Sepulchre is shared by six communities. Three are major stakeholders — the Greek Orthodox Patriarchate, the Roman Catholic Franciscans (the Custody of the Holy Land) and the Armenian Apostolic Church — and three hold smaller rights: the Copts, the Syriac Orthodox and the Ethiopians, the last of whom live on the roof.' },
      { text: 'The Status Quo of 1852 governs everything. It is not a document that lists rules so much as a principle: whatever the arrangement was in 1852, that is the arrangement. Common areas cannot be repaired without unanimous agreement, which is why the building spent much of the twentieth century visibly deteriorating while everyone waited for everyone else.' },
      { text: 'The famous immovable ladder on the ledge above the facade is the emblem of this, but the real cost has been structural. Fire damage from 1808, earthquake damage from 1927, and simple age went untreated for decades.' },
      { h: 'The Edicule, 2016–17' },
      { text: 'By the 1940s the Edicule was in danger of falling apart, and the British Mandate authorities strapped it in an external iron cage. The cage stayed for seventy years — an ugly, humiliating, entirely necessary piece of ironmongery holding the holiest structure in Christianity together.' },
      { text: 'In 2016 the three main communities agreed, finally, to a full structural restoration, carried out by a team from the National Technical University of Athens. The stone was dismantled panel by panel, cleaned, pinned with titanium bars, grouted and reassembled. The cage came off in March 2017.' },
      { text: 'During the work, in October 2016, the marble slab over the burial shelf was lifted. For about sixty hours the team could see, record and sample what lay beneath: fill, a broken older slab with an incised cross, and then the limestone shelf itself. Mortar samples returned a mid-fourth-century date. It was the first time in centuries that anyone had looked.' },
      { h: 'The floor, 2022 to now' },
      { text: 'The second opening is still going on, and archaeologically it is the more important of the two.' },
      { text: 'The church floor needed replacing. Getting agreement for that took years, and the agreement came with a condition that archaeologists had wanted for a century: as each section of paving is lifted for repair, a team may excavate beneath it before the new floor goes down. The work is being carried out by Sapienza University of Rome, section by section, while the church stays open and the liturgies continue around them.' },
      { text: 'The results have been remarkable. Beneath the rotunda: the quarry floor, with cut beds, and Iron Age pottery. Beneath the Katholikon: further quarry surfaces, and the soil layers that accumulated when the hollow was abandoned — the layers that produced the seeds and pollen showing cultivation. Constantinian foundations have been traced. Medieval and modern burials, drains and repairs have been recorded on the way down.' },
      { text: 'Full publication will take years. What has emerged so far confirms the broad sequence that this visualisation shows — quarry, garden and cemetery, Roman fill, Constantinian building — with far more precision than was available before 2022.' },
      { h: 'How the Edicule was taken apart' },
      { text: 'The 2016–17 restoration is worth describing, because it was an unusual piece of engineering in an unusual setting.' },
      { text: 'The team could not simply demolish and rebuild; every original stone had to be kept. So the marble panels were numbered, recorded and lifted off one by one, exposing the rubble core and the fire-damaged masonry inside. The core was cleaned, the voids filled with grout injected at low pressure, and the whole structure stitched together with titanium rods — chosen because titanium will not corrode and swell the way iron does, which is what had cracked the stone in the first place.' },
      { text: 'The panels went back in their recorded positions, and the iron cage that had held the building together since the 1940s was cut away. The work was done in stages around the liturgical calendar, at night where possible, with the church open throughout. It took about ten months.' },
      { h: 'Digging in a working church' },
      { text: 'The 2022 excavation runs under the same constraint, and the constraint shapes the archaeology.' },
      { text: 'Sections of floor are opened only where repair requires it, so the trenches are small, scattered, and dictated by paving joints rather than by research questions. Services continue a few metres away. Everything must be recorded and backfilled to a schedule. It is the opposite of an open-area excavation: the picture is being assembled from keyholes.' },
      { text: 'That it is happening at all is remarkable. The last comparable opportunity came during repairs in the 1960s and 1970s, and the one before that was in the nineteenth century.' },
      { h: 'How the Edicule was taken apart' },
      { text: 'The 2016–17 restoration is worth describing, because it was an unusual piece of engineering carried out in an unusual setting.' },
      { text: 'The team could not simply demolish and rebuild; every original stone had to be kept. So the marble panels were numbered, recorded and lifted off one by one, exposing the rubble core and the fire-damaged masonry inside. The core was cleaned, the voids filled with grout injected under low pressure, and the whole structure stitched together with titanium rods — chosen because it will not corrode and swell the way iron does, which is what had cracked the stone in the first place.' },
      { text: 'The panels then went back in their recorded positions, and the iron cage that had held the building together since the 1940s was cut away. The work was done in stages around the liturgical calendar, at night where possible, with the church open throughout. It took about ten months.' },
      { h: 'Digging in a working church' },
      { text: 'The 2022 excavation is being carried out under the same constraint, and the constraint shapes the archaeology.' },
      { text: 'Sections of floor are opened only where repair requires it, so the trenches are small, scattered and dictated by paving joints rather than by research questions. Services continue a few metres away. Everything must be recorded and backfilled to a schedule. It is the opposite of an open-area excavation, and it means the picture is being assembled from keyholes.' },
      { text: 'That it is happening at all is remarkable. The last comparable opportunity came during repairs in the 1960s and 1970s, and the one before that was in the nineteenth century.' },
      { h: 'What is honestly known' },
      { text: 'It is worth ending by separating the layers of the claim.' },
      { text: 'That this ground was a limestone quarry, later a garden and a rock-cut cemetery outside the first-century city, then filled and built over by Hadrian, then cleared and built on by Constantine: secure. Excavated, dated, published.' },
      { text: 'That the tomb enclosed by the Edicule is a genuine first-century rock-cut tomb, and that it is the tomb Constantine\'s builders identified in the 320s: secure, in the sense that the rock and the fourth-century mortar are both there to be examined.' },
      { text: 'That this particular tomb, among the several in this cemetery, is the tomb of Jesus of Nazareth: not something archaeology can establish. It rests on the tradition of the Jerusalem church, on the argument that a community would not choose an inconvenient spot under a Roman temple inside the city walls unless memory constrained them, and on faith. Those are real arguments. They are not excavation.' },
      { text: 'The honest position is the one the stones support: this is the right kind of place, in the right place, with the right date, and a continuous tradition that reaches back to within three centuries of the event. Beyond that, the ground has nothing more to say.' }
    ],
    debates: [
      'Whether the tradition identifying this specific tomb is reliable is a historical question that archaeology cannot settle, and specialists genuinely differ.',
      'The 2022– excavation results are still being analysed; preliminary reports may be revised on full publication.',
      'The competing Garden Tomb site north of the Damascus Gate is rejected by nearly all archaeologists — its tomb is Iron Age, centuries too early — but remains popular with some visitors.'
    ],
    facts: [['Communities', 'Six, under the Status Quo of 1852'], ['Edicule restored', '2016–17'], ['Excavation', 'Ongoing since 2022']]
  }
};
export default B;
