// CFM — New Testament. Only the weeks with real Jerusalem geography.
window.CFM.weeks = window.CFM.weeks.concat([
{ c: "nt", w: 1, r: "Matthew 1; Luke 1", era: "herod", t: "A priest at the altar of incense",
  p: "Luke opens inside the Temple. Zacharias is chosen by lot to carry incense into the sanctuary \u2014 a duty most priests performed once in a lifetime, if ever. The crowd praying outside stands in the great courts on Herod's platform, watching for him to come out and bless them. He cannot, and the silence is the first sign in the Gospel.",
  s: [["temple", "Luke 1:9"], ["courts", "Luke 1:10"], ["soreg", "Luke 1:8\u201310"]],
  q: ["Why does the detail that Zacharias was chosen by lot matter to how we read his doubt?",
      "The crowd could see the sanctuary but not enter it. How does that shape what a blessing from the priest meant?",
      "What is the effect of Luke beginning his account of Jesus in the Temple and ending it there?"] },

{ c: "nt", w: 2, r: "Matthew 2; Luke 2", era: "herod", t: "Presented in the Temple, and lost in it",
  p: "Two Temple scenes bracket the childhood. Mary and Joseph bring the infant up the southern steps with the offering of the poor, two birds rather than a lamb. Twelve years later the boy stays behind in the courts of the same platform, and it takes his parents a day's travel and three days' searching to find him. Herod, hearing of a rival king, is in his palace at the high western corner of the city.",
  s: [["steps", "Luke 2:22"], ["temple", "Luke 2:24"], ["courts", "Luke 2:46"], ["citadel", "Matthew 2:3"]],
  q: ["The offering Mary brought was the one prescribed for those who could not afford a lamb. What does that establish?",
      "Jesus was found among the teachers, in the outer courts where teaching happened. What does the location tell us about the scene?",
      "Herod's palace and the Temple were both visible from each other. How does that sharpen Matthew 2:3?"] },

{ c: "nt", w: 4, r: "Matthew 3; Mark 1; Luke 3", era: "herod", t: "Down from the city to the Jordan",
  p: "Mark says Jerusalem went out to John. Going out meant descending: the city sits at about 750 metres, and the Jordan where John baptised is nearly 400 metres below sea level. That is a drop of well over a kilometre in a single day's walk east, from cool stone streets into the heat of the rift. The people who came to be baptised had to leave the Temple behind to do it.",
  s: [["jericho", "Mark 1:5"], ["inn", "Matthew 3:5"], ["olivet", "Mark 1:5"]],
  q: ["What does it cost a Jerusalem resident, practically, to go down to John?",
      "Why might a prophet call people out of the city rather than preach inside it?",
      "The descent is physical and the language is moral. Where else does scripture use going down that way?"] },

{ c: "nt", w: 5, r: "Matthew 4; Luke 4\u20135", era: "herod", t: "The pinnacle of the Temple",
  p: "The second temptation happens at a real place. The south-east corner of Herod's platform is where the retaining wall stands highest above the Kidron \u2014 roughly forty-five metres of masonry, and then the valley floor below that. Josephus says a person looking down from it could not see the bottom without growing dizzy. The dare is not abstract: it is a specific corner, above a crowded court, in full view of the city.",
  s: [["pinnacle", "Matthew 4:5"], ["temple", "Luke 4:9"], ["kidron", "Matthew 4:5"]],
  q: ["Why the Temple, of all the places the tempter might choose?",
      "The proposal is a public miracle in the most public spot in Israel. What is being offered, exactly?",
      "How does the answer Jesus gives redefine what trust in God means?"] },

{ c: "nt", w: 6, r: "John 2\u20134", era: "herod", t: "The first cleansing of the courts",
  p: "The trade Jesus overturns was in the outer court, not the sanctuary \u2014 the wide public plaza where pilgrims exchanged foreign coin for Temple currency and bought unblemished animals. It was a service, and it had become a market. The saying about raising the temple in three days is spoken standing inside a building project already forty-six years old and still unfinished. Nicodemus comes to him by night in the Upper City above.",
  s: [["courts", "John 2:14"], ["stoa", "John 2:14\u201316"], ["temple", "John 2:20"], ["upper", "John 3:1\u20132"]],
  q: ["The money changers served a real need. What made the arrangement wrong?",
      "Herod's Temple had been under construction for forty-six years. How does that change the force of John 2:20?",
      "Why does John place Nicodemus immediately after the cleansing?"] },

{ c: "nt", w: 13, r: "Easter", era: "herod", t: "The whole of it, in one square kilometre",
  p: "Everything from the Last Supper to the empty tomb happens within about a kilometre. The Upper Room sits high on the south-west hill; Gethsemane is across the Kidron to the east; the high priest's house is back up the western slope; Pilate is at the citadel; Golgotha is a quarry face just outside the north-west wall. A person could walk the entire sequence in under two hours \u2014 and Jesus walked it at night, under arrest, uphill and down, three times across the same city.",
  s: [["cenacle", "Luke 22:12"], ["gethsemane", "Mark 14:32"], ["caiaphas", "Mark 14:53"], ["praet", "John 19:13"], ["golg", "John 19:17"], ["tomb", "John 19:41"]],
  q: ["Trace the night on the map. What does the sheer compactness of it add to the account?",
      "Golgotha and the tomb were in the same abandoned quarry, minutes apart. Why does that matter for the burial account?",
      "Which single site would you take a class to first, and why that one?"] },

{ c: "nt", w: 14, r: "Matthew 14; Mark 6; John 5\u20136", era: "herod", t: "The pool with five porches",
  p: "John 5 describes a twin reservoir surrounded by five porticoes, near the sheep gate on the north side. Sceptics called the five porches a symbolic invention until excavation found exactly that: two pools separated by a central partition, with colonnades on four sides and one along the middle. The healing happens at a place where the sick gathered because water occasionally stirred, and where a man had waited thirty-eight years for someone faster than him to stop coming first.",
  s: [["beth", "John 5:2"], ["lions", "John 5:2"], ["temple", "John 5:14"]],
  q: ["What does the excavated shape of the pool tell us about the way John reports detail?",
      "The man's answer to whether he wants to be healed is not yes. What is it?",
      "Jesus finds him afterwards in the Temple. Why does John record the second meeting?"] },

{ c: "nt", w: 16, r: "Matthew 18; Luke 10", era: "herod", t: "The road down to Jericho",
  p: "A certain man went down from Jerusalem to Jericho \u2014 and down is the exact word. The road falls more than a kilometre in twenty-seven, through waterless limestone with blind corners every few hundred metres. Robbery was the ordinary risk of that road, not a plot device. The priest and the Levite are going the other way, up to the city and their duties. Bethany, where Mary and Martha receive him, is on the same road at the top of the climb.",
  s: [["jericho", "Luke 10:30"], ["inn", "Luke 10:30\u201335"], ["bethany", "Luke 10:38"], ["olivet", "Luke 10:38"]],
  q: ["What does the terrain add to the parable that a flat road would not?",
      "The priest and Levite are travelling up toward the Temple. Does that change how you read their choice?",
      "Bethany is the last stop before the city. What does it mean that this was where Jesus stayed?"] },

{ c: "nt", w: 17, r: "John 7\u201310", era: "herod", t: "Two feasts, and the water from Siloam",
  p: "These chapters are anchored to two festivals and their rituals. At Tabernacles a priest carried water up from the Pool of Siloam each morning and poured it out at the altar; on the last day of the feast Jesus stands in the courts and offers living water. Chapters later he sends a blind man down to that same pool to wash. At the winter feast of Dedication he is teaching in Solomon's Porch, the eastern colonnade \u2014 the sheltered side, because it was cold.",
  s: [["siloam", "John 9:7"], ["courts", "John 7:37"], ["temple", "John 8:2"], ["porch", "John 10:22\u201323"], ["tunnel", "John 9:7"]],
  q: ["Knowing the water ceremony, what is Jesus claiming in John 7:37\u201338?",
      "The blind man had to walk downhill through the city to reach Siloam. What does the obedience cost him?",
      "John notes that it was winter and Jesus walked in the eastern porch. Why keep a detail like that?"] },

{ c: "nt", w: 18, r: "Luke 12\u201317; John 11", era: "herod", t: "Bethany, and the decision to kill him",
  p: "Lazarus is raised three kilometres from the Temple, close enough that mourners from Jerusalem were present and word reached the chief priests the same day. The council that decides Jesus must die meets beside the platform. Bethany matters geographically: it is over the ridge, so the city cannot see it and it cannot see the city \u2014 which is why the raising is reported rather than witnessed, and why the reaction is political.",
  s: [["bethany", "John 11:1"], ["olivet", "John 11:18"], ["sanhedrin", "John 11:47"], ["temple", "John 11:48"]],
  q: ["Why does John specify that Bethany was about fifteen furlongs from Jerusalem?",
      "The council's stated fear is that the Romans will take away the Temple and the nation. How does that shape their logic?",
      "What does it mean that the most public of the signs happened just out of the city's sight?"] },

{ c: "nt", w: 19, r: "Matthew 19\u201320; Mark 10; Luke 18", era: "herod", t: "Going up to Jerusalem",
  p: "Three Gospels use the same phrase for the last journey, and it is literal. From Jericho the road climbs a thousand metres. Blind Bartimaeus is sitting at the bottom of that ascent; the request for the best seats in the kingdom is made on the way up it. The disciples are walking uphill toward a city where Jesus has just told them he will be killed, and are arguing about rank.",
  s: [["jericho", "Mark 10:46"], ["inn", "Mark 10:32"], ["bethany", "Matthew 20:29"], ["tm", "Mark 10:33"]],
  q: ["Mark says they were on the way up and the disciples were afraid. What were they afraid of?",
      "How does a hard physical climb change the tone of the conversation about who is greatest?",
      "Bartimaeus asks for sight; James and John ask for glory. What separates the two requests?"] },

{ c: "nt", w: 20, r: "Matthew 21\u201323; Mark 11; Luke 19\u201320; John 12", era: "herod", t: "Down Olivet and into the courts",
  p: "This is the week the map was built for. From Bethphage the road crests the Mount of Olives, and the whole Temple platform appears at once, directly opposite and slightly below. The descent to the Kidron is about 200 metres in less than a kilometre, then the climb back up to the gates. Jesus enters, looks around the courts, and leaves; he returns the next morning and overturns the tables. The fig tree and the cleansing are two halves of one act.",
  s: [["bethphage", "Matthew 21:1"], ["olivet", "Mark 11:1"], ["kidron", "Luke 19:37"], ["golden", "Matthew 21:10"], ["courts", "Mark 11:15"], ["stoa", "Matthew 21:12"]],
  q: ["Stand at the crest of Olivet on the map. Why did Jesus weep at that exact point on the road?",
      "Mark separates the entry from the cleansing by a night. Why does that ordering matter?",
      "The trade was in the court open to Gentiles. How does that inform 'a house of prayer for all nations'?"] },

{ c: "nt", w: 21, r: "JS\u2013M 1; Matthew 24\u201325; Mark 12\u201313; Luke 21", era: "herod", t: "Not one stone upon another",
  p: "The Olivet discourse is delivered from the one place where the whole Temple is in view. They have come out of the courts, crossed the Kidron and climbed the slope; a disciple looks back at the stonework and remarks on it. The prophecy is about the building they are looking at, and it came true within forty years. The stones Titus's soldiers pushed off the platform in AD 70 still lie on the Herodian street below Robinson's Arch.",
  s: [["olivet", "Matthew 24:3"], ["tm", "Mark 13:1"], ["rob", "Luke 21:6"], ["kidron", "Mark 13:3"], ["ww", "Matthew 24:2"]],
  q: ["Why deliver this discourse from Olivet rather than inside the Temple?",
      "The fallen stones are still visible today. What does standing over them do to the reading?",
      "How do you distinguish, in these chapters, what was fulfilled in AD 70 from what was not?"] },

{ c: "nt", w: 22, r: "Matthew 26; Mark 14; John 13", era: "herod", t: "The Upper Room, uphill from the Temple",
  p: "The supper is on the high south-west hill, in the wealthier Upper City \u2014 a house with an upper storey large enough for thirteen. Anointing at Bethany opens the week; the walk to Gethsemane closes the evening. Judas leaves the room and goes downhill to the priests near the Temple, and comes back up with a detachment. The betrayal is measured in minutes of walking, in a city where everyone concerned was within earshot of everyone else.",
  s: [["cenacle", "Mark 14:15"], ["bethany", "Matthew 26:6"], ["upper", "Matthew 26:18"], ["caiaphas", "Matthew 26:14"], ["gethsemane", "Mark 14:26"]],
  q: ["The room was borrowed and prepared in advance. What does that arrangement suggest?",
      "Judas's errand was a short walk. Does the proximity change how you read his decision?",
      "Why does the meal happen at the top of the city and the arrest at the bottom of the valley?"] },

{ c: "nt", w: 23, r: "John 14\u201317", era: "herod", t: "Spoken on the way down",
  p: "At the end of chapter 14 Jesus says arise, let us go hence \u2014 and chapter 18 opens with them crossing the brook Kidron. Three chapters of the farewell discourse are most naturally read as spoken on the move: out of the Upper Room, down through the sleeping city, past the Temple, down into the ravine and up the far bank into the olive grove. The vine and the branches is said walking past vineyards on that slope, at night, at Passover.",
  s: [["cenacle", "John 14:31"], ["tyro", "John 15:1"], ["kidron", "John 14:31"], ["gethsemane", "John 14:31"], ["temple", "John 17:1"]],
  q: ["How does reading John 15\u201317 as spoken on a night walk change their tone?",
      "The route passes directly beneath the Temple. What might the priestly prayer of John 17 owe to that?",
      "What is gained by praying for the disciples' unity within sight of the place where he will be tried?"] },

{ c: "nt", w: 24, r: "Luke 22; John 18", era: "herod", t: "Arrest in the valley, trial on the hill",
  p: "Gethsemane lay across the Kidron Valley on the lower Mount of Olives. Its precise ancient boundary and sightlines are uncertain, but the garden setting offered a familiar place where Jesus withdrew and where Judas knew to find him. From there the party climbs back up the western slope to the high priest's house in the Upper City, where a courtyard with a fire and a gate kept by a servant girl is exactly the domestic architecture excavated in that quarter. Peter's denial happens in the open air of a wealthy house.",
  s: [["gethsemane", "John 18:1\u201312"], ["kidron", "John 18:1"], ["caiaphas", "John 18:13"], ["upper", "Luke 22:54"], ["sanhedrin", "Luke 22:66"]],
  q: ["What does the seclusion of Gethsemane tell us about how the arrest was arranged?",
      "The denial happens in a courtyard, within hearing of the trial. How does that setting sharpen it?",
      "Why is Jesus taken first to a private house and only later to the council?"] },

{ c: "nt", w: 25, r: "Matthew 27; Mark 15; Luke 23; John 19", era: "herod", t: "Outside the gate",
  p: "Execution had to happen outside the wall, and Golgotha was: a quarry face beside a road on the north-west, with old rock-cut tombs in the same disused ground. The Second Wall ran between it and the city. Three centuries later the city grew past it, which is why the site is now well inside the Old City and inside a church \u2014 the single fact that most confuses visitors. Judas's field is on the opposite, southern side, above the Hinnom.",
  s: [["praet", "John 19:13"], ["via", "Mark 15:20"], ["golg", "John 19:17"], ["tomb", "John 19:41"], ["akeldama", "Matthew 27:8"], ["hinnom", "Matthew 27:10"]],
  q: ["Why does it matter, theologically, that he suffered outside the gate?",
      "The Holy Sepulchre is inside the walls today. How would you explain that to someone standing there?",
      "The tomb was in the same quarry as the cross. What does the nearness make possible in the accounts?"] },

{ c: "nt", w: 26, r: "Matthew 28; Mark 16; Luke 24; John 20\u201321", era: "herod", t: "An empty tomb, and a road out",
  p: "The women come at first light to a tomb minutes from where they had watched him die. Then the movement reverses: two disciples walk out to Emmaus and back the same evening, a round trip of some twenty kilometres, because the news would not keep. Luke closes where he began, with the ascension out past Bethany on the far side of Olivet \u2014 the last thing the Gospel does is take them out of the city.",
  s: [["tomb", "John 20:1"], ["golg", "Matthew 28:1"], ["cenacle", "John 20:19"], ["bethany", "Luke 24:50"], ["ascension", "Luke 24:50\u201351"]],
  q: ["The tomb was a short walk from the cross. How does that affect the argument that the body was moved?",
      "Emmaus and back in one evening is a serious walk. What does that tell you about the disciples' state?",
      "Luke ends at Bethany, over the ridge from the Temple. Why finish there?"] },

{ c: "nt", w: 27, r: "Acts 1\u20135", era: "herod", t: "Pentecost, and where three thousand were baptised",
  p: "Acts begins on Olivet and moves immediately back to the Upper Room. The southern Temple approaches contained dozens of stepped ritual baths that show how large crowds could immerse near the Temple. They offer one plausible setting for Acts 2, although the text does not say where or how the baptisms occurred. The apostles then teach daily in Solomon's Porch, on the platform, in the institution they are accused of undermining.",
  s: [["ascension", "Acts 1:12"], ["cenacle", "Acts 1:13"], ["mikvaot", "Acts 2:41"], ["steps", "Acts 2:46"], ["porch", "Acts 3:11"], ["temple", "Acts 3:2"]],
  q: ["What does the archaeology of the ritual baths suggest about Acts 2:41?",
      "The early church met daily in the Temple. What does that continuity mean?",
      "The lame man sat at a Temple gate to beg. Why was that the right place for him to be?"] },

{ c: "nt", w: 28, r: "Acts 6\u20139", era: "herod", t: "Stephen, taken outside the wall",
  p: "Stephen's speech is an argument about place: that God was with Abraham before there was a Temple and with Israel in a tent before there was a building. The council hears it inside the Temple precinct, and the stoning happens outside the wall, as the law required. Saul, watching the clothes, then sets out on the road north from the city \u2014 the same gate a modern visitor uses for the bus station.",
  s: [["sanhedrin", "Acts 6:12"], ["temple", "Acts 6:13"], ["stephen", "Acts 7:58"], ["dam", "Acts 9:1\u20132"]],
  q: ["Stephen is accused of speaking against the Temple. What does he actually say about it?",
      "Why did executions have to take place outside the city, and what does that pattern echo?",
      "Saul leaves from Jerusalem toward Damascus. How does that direction matter to the story that follows?"] },

{ c: "nt", w: 29, r: "Acts 10\u201315", era: "herod", t: "The council that opened the church",
  p: "The decision that Gentile converts need not become Jews first is taken in Jerusalem, a few steps from a stone barrier in the Temple courts inscribed with a death threat against any Gentile who passed it. That barrier is not a metaphor: two of its inscriptions survive in museums. The council's ruling is made in the one city where the wall between Jew and Gentile was a physical object you could stand in front of.",
  s: [["soreg", "Acts 15:1"], ["courts", "Acts 15:5"], ["sanhedrin", "Acts 15:6"], ["temple", "Acts 15:21"]],
  q: ["What does the surviving soreg inscription add to Ephesians 2:14?",
      "Why was Jerusalem the necessary place for this decision to be made?",
      "The ruling keeps four requirements. What holds them together?"] },

{ c: "nt", w: 30, r: "Acts 16\u201321", era: "herod", t: "A riot in the courts, and the stairs down from the fortress",
  p: "Paul is accused of bringing a Gentile past the barrier, and the crowd drags him out of the inner court to kill him. The rescue works because of the architecture: the Antonia Fortress stood at the platform's north-west corner with stairs running straight down into the court, so a Roman garrison could be in the crowd within a minute. Paul then asks to speak from those very stairs, and addresses the mob in Hebrew.",
  s: [["courts", "Acts 21:27"], ["soreg", "Acts 21:28"], ["antonia", "Acts 21:32"], ["temple", "Acts 21:26"], ["tm", "Acts 21:30"]],
  q: ["How does the layout of the Antonia explain the speed of Paul's rescue?",
      "Paul had gone to the Temple to complete a vow. Why does that detail matter to the charge?",
      "He addresses the crowd from the stairs, above them. What does that vantage give him?"] },

{ c: "nt", w: 31, r: "Acts 22\u201328", era: "herod", t: "Held in the fortress, and moved out by night",
  p: "Paul spends these chapters in Roman custody at the Antonia, a few metres from the Temple he was accused of defiling. He is brought down to the council, sent back up, and then moved out of the city by night with an escort of nearly five hundred men because forty men have sworn not to eat until he is dead. The road to Caesarea runs north-west; he never sees Jerusalem again.",
  s: [["antonia", "Acts 22:24"], ["sanhedrin", "Acts 23:1"], ["temple", "Acts 24:12"], ["dam", "Acts 23:23"]],
  q: ["Why does Paul's Roman citizenship change the whole course of the narrative?",
      "The plot required him to be moved between two buildings a short walk apart. What does the danger of that walk suggest?",
      "Paul leaves Jerusalem under guard and never returns. How does that close the book's Jerusalem story?"] },

{ c: "nt", w: 39, r: "Galatians", era: "herod", t: "Three visits to one city",
  p: "Galatians is partly an argument about Paul's own geography: he insists he did not go up to Jerusalem for three years, then went for fifteen days, then not again for fourteen years. He is establishing that his commission did not come from the leaders on that hill. The confrontation with Peter happens elsewhere, in Antioch, over whether the Jerusalem practice binds everyone \u2014 the same question the soreg barrier asked in stone.",
  s: [["tm", "Galatians 1:18"], ["sanhedrin", "Galatians 2:1"], ["soreg", "Galatians 2:11\u201314"]],
  q: ["Why is Paul so precise about when he did and did not go to Jerusalem?",
      "What is at stake in whether authority runs outward from one city?",
      "How does the physical barrier in the Temple courts illuminate Paul's argument about the law?"] },

{ c: "nt", w: 45, r: "Hebrews 7\u201313", era: "herod", t: "Without the camp",
  p: "Hebrews reads the Temple ritual as pattern, and then makes a geographical claim: Jesus suffered outside the gate, so let us go out to him, outside the camp. The writer is pointing at real ground \u2014 the quarry on the north-west, beyond the wall of that day, where the refuse and the tombs and the executions were. The letter's whole argument about a better sacrifice turns on a location that was deliberately, legally, outside.",
  s: [["temple", "Hebrews 9:1\u20135"], ["courts", "Hebrews 9:6"], ["golg", "Hebrews 13:12"], ["hinnom", "Hebrews 13:13"]],
  q: ["What does outside the camp mean concretely, and what does it ask of the reader?",
      "Hebrews describes the sanctuary in the present tense. What might that suggest about when it was written?",
      "Why is the location of the crucifixion, not just its fact, part of the theology here?"] },

{ c: "nt", w: 51, r: "Revelation 15\u201322", era: "today", t: "The city measured against the city",
  p: "Revelation's new Jerusalem is measured: twelve thousand furlongs on each side, a cube roughly 2,200 kilometres across, with walls of jasper and no temple in it because God is its temple. Set that against the real thing on this map \u2014 a walled city of about one square kilometre with a single sacred platform at its heart. The vision is not a description of the place; it is a deliberate, almost comic enlargement of it.",
  s: [["newjer", "Revelation 21:16"], ["tm", "Revelation 21:22"], ["golden", "Revelation 21:21"], ["ezekwater", "Revelation 22:1"]],
  q: ["What is the effect of giving the vision exact measurements?",
      "The city has no temple. What does that resolve about everything the Temple was for?",
      "Compare the river of Revelation 22 with Ezekiel 47. What has changed?"] }
]);
