// CFM — Old Testament, Book of Mormon, Doctrine and Covenants.
window.CFM.weeks = window.CFM.weeks.concat([

// ---------------- Old Testament ----------------
{ c: "ot", w: 21, r: "Joshua 1\u20138; 23\u201324", era: "canaan", t: "The city Israel did not take",
  p: "Joshua's campaigns run past Jerusalem without taking it. The Jebusite city was small \u2014 about five hectares on a narrow ridge \u2014 but it sat above a spring, with ravines on two sides and a single vulnerable approach from the north. That is why it held out for another four centuries while easier towns fell, and why the eventual capture is remembered as David's achievement rather than Joshua's.",
  s: [["cod", "Joshua 15:63", "context"], ["gihon", "Joshua 15:8", "context"], ["hinnom", "Joshua 15:8", "context"], ["kidron", "Joshua 18:16", "context"]],
  q: ["Look at the ridge on the map. What made this small city so hard to take?",
      "Joshua 15:63 records a failure inside a book of victories. Why keep it?",
      "How does the geography of the spring explain the city's survival?"] },

{ c: "ot", w: 22, r: "Judges 2\u20134; 6\u20138; 13\u201316", era: "canaan", t: "Jebus, between the tribes",
  p: "Judges reports both that Judah struck Jerusalem and that the Jebusites went on living there \u2014 the kind of double statement that makes sense once you see the site. The ridge sits exactly on the boundary between Judah and Benjamin, claimed by both and controlled by neither. It stayed a foreign enclave inside Israel for the whole period of the judges, which is part of why David's later choice of it as a capital was politically shrewd.",
  s: [["cod", "Judges 1:8", "context"], ["millo", "Judges 1:21", "context"], ["kidron", "Judges 19:10", "context"]],
  q: ["Why would a city on a tribal boundary be a useful capital later on?",
      "What does the persistence of a Jebusite enclave say about the period of the judges?",
      "How do the two accounts in Judges 1 fit together?"] },

{ c: "ot", w: 25, r: "1 Samuel 17\u201318; 24\u201326; 2 Samuel 5\u20137", era: "david", t: "Taken by way of the water shaft",
  p: "The capture in 2 Samuel 5 turns on a word, tsinnor, usually translated gutter or water shaft. Beneath the ridge runs a system that let the city reach the Gihon Spring without going outside its wall \u2014 shafts, tunnels and a fortified pool. Whatever exactly Joab climbed, the point is that the city's one weakness was the thing that made it habitable. David then builds inward from the Millo, and the ridge becomes the City of David.",
  s: [["warren", "2 Samuel 5:8"], ["gihon", "2 Samuel 5:8"], ["cod", "2 Samuel 5:7"], ["millo", "2 Samuel 5:9"], ["ophel", "2 Samuel 6:12"]],
  q: ["Why does a city's water supply double as its weakest point?",
      "David chose a city belonging to neither Judah nor Israel. What did that solve?",
      "The ark is brought up to a city with no temple yet. What does 2 Samuel 7 do with that?"] },

{ c: "ot", w: 26, r: "2 Samuel 11\u201312; 1 Kings 3; 6\u20139; 11", era: "david", t: "A roof above the city, a threshing floor above that",
  p: "David sees Bathsheba from the roof of his house; 2 Samuel 11:2 places his house in the City of David, on the ridge above the terraced houses below, but the palace's exact footprint has not been excavated \u2014 its identification at the ridge's high northern end reflects one influential reading (Eilat Mazar's 'Large Stone Structure' proposal), which other archaeologists dispute or date differently. Solomon then builds the Temple on the threshing floor his father bought (2 Samuel 24:18\u201325; 1 Kings 6:1), traditionally identified with the bedrock now under the Dome of the Rock, though the Temple's precise footprint and its relation to that rock are inferred from later sources, not fixed by excavation. Later platforms, including Herod's expansion, rose on the same high ground, but 'built around that rock' names the traditional identification, not a confirmed archaeological finding.",
  s: [["millo", "2 Samuel 11:2"], ["cod", "2 Samuel 11:2"], ["royalq", "1 Kings 9:15"], ["soltemple", "1 Kings 6:1"], ["ophel", "1 Kings 8:1"]],
  q: ["What does the terracing of the ridge add to the account in 2 Samuel 11?",
      "Solomon's Temple and his palace complex sat above the old city. What did that arrangement signal?",
      "Why does the site of the Temple matter so much to everything that follows?"] },

{ c: "ot", w: 29, r: "2 Kings 16\u201325", era: "hezekiah", t: "A tunnel, a siege, and a breach",
  p: "These chapters contain the best-documented engineering project in the Hebrew Bible. Facing Sennacherib, Hezekiah cuts 533 metres of tunnel from the Gihon Spring to a pool inside the new wall, working from both ends toward the middle. The city survives. A century and a half later Nebuchadnezzar's army breaks the wall on the vulnerable north, burns the Temple and takes the people away \u2014 and the tunnel is still there, still carrying water.",
  s: [["tunnel", "2 Kings 20:20"], ["gihon", "2 Kings 20:20"], ["siloam", "2 Kings 20:20"], ["broad", "2 Kings 18:13"], ["fishgate", "2 Kings 25:4"], ["soltemple", "2 Kings 25:9"]],
  q: ["Hezekiah's preparation was practical and his prayer was total. How do the two fit together?",
      "The city fell on the north side, where the ground is level. What does terrain determine here?",
      "Both deliverance and destruction happen at the same walls. What does the pairing teach?"] },

{ c: "ot", w: 30, r: "2 Chronicles 14\u201320; 26; 30", era: "hezekiah", t: "Towers, and a Passover for a doubled city",
  p: "Chronicles records the building programme that the map shows: Uzziah's towers at the corners and gates, and Hezekiah's Passover for a city that had grown substantially in this period, partly through refugees from the fallen north. That growth is why the Broad Wall exists \u2014 seven metres thick, thrown across the Western Hill in haste, with houses demolished under it to make the line. The invitation in 2 Chronicles 30 is to a city that had just doubled in size.",
  s: [["broad", "2 Chronicles 32:5", "context"], ["mishneh", "2 Chronicles 32:5", "context"], ["fishgate", "2 Chronicles 26:9"], ["soltemple", "2 Chronicles 30:1"], ["tunnel", "2 Chronicles 32:30", "context"]],
  q: ["What does the Broad Wall tell us about how fast the city grew?",
      "Refugees from the north are invited to keep Passover in the south. What is being repaired?",
      "Chronicles credits Hezekiah with both waterworks and worship. Why report them together?"] },

{ c: "ot", w: 31, r: "Ezra 1; 3\u20137; Nehemiah 2; 4\u20136; 8", era: "return", t: "A night ride around the ruins",
  p: "Nehemiah 2 is a survey. He goes out at night by the valley gate, past the dragon well and the dung gate, up the Kidron side, and finds the rubble so deep his animal cannot pass. The wall he then builds runs higher up the eastern slope than the old one \u2014 the collapsed terraces below were beyond saving, and the excavated line proves it. Ezra reads the law at the water gate, above the spring, where crowds naturally gathered.",
  s: [["dung", "Nehemiah 2:13"], ["kidron", "Nehemiah 2:14"], ["neh", "Nehemiah 4:6"], ["watergate", "Nehemiah 8:1"], ["zerub", "Ezra 3:10"], ["gihon", "Nehemiah 2:14"]],
  q: ["Why does Nehemiah inspect the walls at night and tell no one?",
      "His wall is smaller than the one it replaced. What does that admission cost, and why make it?",
      "The law is read at a gate rather than in the Temple. What does the setting say about the reading?"] },

{ c: "ot", w: 34, r: "Psalms 1\u20132; 8; 19\u201333; 40; 46", era: "hezekiah", t: "A river for a city with no river",
  p: "Psalm 46 promises a river whose streams make glad the city of God \u2014 written about a city that has no river at all. Jerusalem's water is one spring in a ravine and whatever rain the cisterns catch. That is precisely the point: the psalm's confidence is not in a resource the city possesses but in one it does not. Read it standing at the Gihon, which is a modest trickle, and the metaphor sharpens.",
  s: [["gihon", "Psalm 46:4"], ["zion", "Psalm 46:4"], ["cod", "Psalm 46:5"], ["soltemple", "Psalm 24:3"]],
  q: ["What does it mean to promise a river to a city built on a single spring?",
      "Psalm 24 asks who may ascend the hill. What did ascending physically involve?",
      "How does knowing the city's real water supply change Psalm 46?"] },

{ c: "ot", w: 36, r: "Psalms 102\u2013103; 110; 116\u2013119; 127\u2013128; 135\u2013139; 146\u2013150", era: "herod", t: "Sung on the way up",
  p: "Many of these psalms were pilgrimage songs, sung on the climb to the city and up the final steps. Psalm 118, the last of the Hallel, was sung at Passover \u2014 the stone the builders refused, the gates of righteousness, blessed is he that cometh. Pilgrims sang it on the southern steps \u2014 the steps on this map are Herod's, five centuries after the psalms were written, but the climb and the practice are the same \u2014 and their treads alternate in depth, producing a measured ascent whose intended purpose is unknown. Centuries later a crowd sang it again on the road down Olivet.",
  s: [["steps", "Psalm 118:19"], ["mikvaot", "Psalm 118:20"], ["temple", "Psalm 118:22"], ["olivet", "Psalm 118:26"]],
  q: ["What difference does it make that these words were sung while walking uphill?",
      "Psalm 118:26 is quoted on Palm Sunday. Why was that line already in everyone's mouth?",
      "The steps were built to slow people down. What does that intend?"] },

{ c: "ot", w: 38, r: "Isaiah 1\u201312", era: "hezekiah", t: "A vision in the Temple, a sign at the conduit",
  p: "Isaiah's call happens inside the Temple, with smoke and shaking and a live coal from the altar. Two chapters later he is told to meet the king at a specific piece of infrastructure: the end of the conduit of the upper pool, on the road to the fuller's field. That is a real place on the western side of the water system, and the setting is deliberate \u2014 the prophet confronts a king worrying about water supply, at the water supply.",
  s: [["soltemple", "Isaiah 6:1"], ["siloam", "Isaiah 7:3"], ["gihon", "Isaiah 8:6"], ["tunnel", "Isaiah 7:3"]],
  q: ["Why does Isaiah's commission happen in the Temple rather than in private?",
      "Isaiah 7 names an exact spot for the meeting. What does that specificity accomplish?",
      "The waters of Shiloah go softly. What is Isaiah contrasting them with?"] },

{ c: "ot", w: 39, r: "Isaiah 13\u201314; 22; 24\u201330; 35", era: "hezekiah", t: "The pool between the two walls",
  p: "Isaiah 22 is the most map-specific chapter in the book. He describes the city gathering water in the lower pool, breaking down houses to fortify the wall, and making a ditch between the two walls \u2014 and then condemns them for doing all of it without looking to God. Several items in that list \u2014 the pool, the wall repairs, the ditch \u2014 have correlates in the archaeological record; not every detail can be matched one-to-one. The chapter also names Shebna, whose rock-cut tomb Isaiah says he cut too grandly for a servant.",
  s: [["siloam", "Isaiah 22:9"], ["broad", "Isaiah 22:10"], ["tunnel", "Isaiah 22:11"], ["absalom", "Isaiah 22:16"], ["mishneh", "Isaiah 22:10"]],
  q: ["Isaiah does not say the engineering was wrong. What does he say was missing?",
      "How does it change the chapter to know that these works have been found?",
      "Why single out a man's tomb as a symbol of the whole problem?"] },

{ c: "ot", w: 42, r: "Isaiah 58\u201366", era: "return", t: "Beautiful garments for a ruined city",
  p: "These chapters address a city in rubble and speak to it as though it were adorned. Isaiah tells Zion to awake and put on her beautiful garments, promises that the waste places will be rebuilt, and calls the watchmen on her walls to give God no rest \u2014 walls that at the time were broken down. The prophecy is aimed at people who could see the actual damage on the actual slope.",
  s: [["neh", "Isaiah 58:12"], ["zion", "Isaiah 60:14"], ["zerub", "Isaiah 66:1"], ["cod", "Isaiah 62:6"]],
  q: ["What is the effect of addressing a ruined city in the language of adornment?",
      "Isaiah 66:1 asks what house could contain God. How does that reframe the rebuilding?",
      "Who are the watchmen on the walls, and what are they asked to do?"] },

{ c: "ot", w: 43, r: "Jeremiah 1\u20133; 7; 16\u201318; 20", era: "hezekiah", t: "Preaching at the gate of the house",
  p: "Jeremiah is told to stand in the gate of the Lord's house and tell the people entering to worship that the building will not save them. He does it at the Temple gate, to the crowd going in, and it nearly costs him his life. He also points south: the valley of Hinnom, where children had been burned at Topheth, will be renamed the valley of slaughter, and he is sent to the potter's house to watch a vessel be broken and remade. Both locations are minutes apart, and he uses the geography as the argument.",
  s: [["soltemple", "Jeremiah 7:2"], ["royalq", "Jeremiah 7:4"], ["hinnom", "Jeremiah 7:31"], ["akeldama", "Jeremiah 18:2"], ["dung", "Jeremiah 7:32"]],
  q: ["Why deliver the sermon at the gate rather than inside or outside?",
      "The people said the Temple would protect them. What was the answer?",
      "Hinnom becomes Gehenna. How did a real valley turn into a word for judgement?"] },

{ c: "ot", w: 44, r: "Jeremiah 31\u201333; 36\u201338; Lamentations 1; 3", era: "hezekiah", t: "A cistern, a siege, and a lament over the stones",
  p: "Jeremiah spends the siege inside the city, and part of it inside a cistern in the court of the guard, sunk into mud. He buys a field while the Babylonian army is at the wall. Jeremiah is questioned at the gate of Benjamin on his way out of the city. Then the wall breaks, the Temple burns, and Lamentations is written by someone looking at the result: the gates sunk into the ground, the roads to Zion empty, the stones of the sanctuary poured out into the streets.",
  s: [["royalq", "Jeremiah 38:6"], ["soltemple", "Jeremiah 32:9"], ["fishgate", "Jeremiah 37:13"], ["zion", "Lamentations 1:4"], ["kidron", "Lamentations 1:4"]],
  q: ["Jeremiah buys a field during a siege. What is the purchase for?",
      "Lamentations describes specific damage. What does the specificity do to the grief?",
      "How do Jeremiah 31 and Lamentations 3 hold hope and ruin together?"] },

{ c: "ot", w: 45, r: "Ezekiel 1\u20133; 33\u201334; 36\u201337; 47", era: "return", t: "Water running east out of the Temple",
  p: "Ezekiel 47 is a vision with a real gradient behind it. Water comes out from under the Temple's threshold, runs east, and deepens \u2014 ankles, knees, loins, then beyond measuring. Follow that line on the map and it drops into the Kidron and runs down through the desert to the Dead Sea, thirty kilometres away and 400 metres below. The vision's promise is that the saltiest water on earth will be healed by a stream from a hill.",
  s: [["zerub", "Ezekiel 47:1"], ["ezekwater", "Ezekiel 47:3"], ["kidron", "Ezekiel 47:8"], ["golden", "Ezekiel 47:2"]],
  q: ["Trace the water's route on the map. Why does the direction east matter?",
      "The river deepens without tributaries. What is that detail saying?",
      "Ezekiel sees a sealed eastern gate. What does the seal mean here?"] },

{ c: "ot", w: 46, r: "Daniel 1\u20137", era: "return", t: "Praying toward a city that is gone",
  p: "Daniel's window faces Jerusalem, and he opens it three times a day to pray toward a city that at that moment is a burnt ruin nine hundred kilometres away. The vessels from the Temple are brought out onto a Babylonian banquet table \u2014 the night Belshazzar reads the writing on the wall. The whole book turns on people who keep orienting themselves toward a place they cannot see and may never return to.",
  s: [["soltemple", "Daniel 1:2"], ["zion", "Daniel 6:10"], ["cod", "Daniel 5:3"]],
  q: ["What does it mean to pray toward a place that has been destroyed?",
      "The Temple vessels appear in Daniel 5. Why does their use provoke judgement?",
      "How does exile change the meaning of a fixed direction for prayer?"] },

{ c: "ot", w: 49, r: "Micah; Nahum; Habakkuk; Zephaniah", era: "hezekiah", t: "Zion plowed as a field",
  p: "Micah says Zion will be plowed as a field and the mountain of the house become a wooded height \u2014 the most physical of the judgements, and it was quoted a century later as a precedent for tolerating a prophet who said such things. Zephaniah takes the reader on a route through the city: a cry from the fish gate, a howling from the second quarter, a crash from the hills. That is a description of an army entering from the north.",
  s: [["zion", "Micah 3:12"], ["soltemple", "Micah 4:1"], ["fishgate", "Zephaniah 1:10"], ["mishneh", "Zephaniah 1:10"], ["broad", "Zephaniah 1:10"]],
  q: ["Why is Micah's image agricultural rather than military?",
      "Zephaniah names gates and quarters in order. What is he tracing?",
      "Micah 3:12 and 4:1 sit side by side. How do you read them together?"] },

{ c: "ot", w: 50, r: "Haggai; Zechariah 1\u20133; 7\u201314", era: "return", t: "The mountain that splits",
  p: "Haggai addresses people who have built their own houses and left the Temple a foundation, and the men who remembered Solomon's building wept when they saw the replacement. Zechariah 14 then makes the boldest geographical claim in the prophets: the Lord's feet will stand on the Mount of Olives and the mountain will split east and west, opening a valley where there is now a ridge. Living water will go out from the city, summer and winter.",
  s: [["zerub", "Haggai 1:4"], ["soltemple", "Haggai 2:3"], ["olivet", "Zechariah 14:4"], ["kidron", "Zechariah 14:4"], ["ezekwater", "Zechariah 14:8"]],
  q: ["Why did the old men weep at the new Temple, and what does Haggai say to them?",
      "Zechariah 14 splits a real mountain. What does the picture accomplish?",
      "Living water in summer as well as winter \u2014 why is that the promise in this climate?"] },

{ c: "ot", w: 51, r: "Malachi", era: "return", t: "Suddenly come to his temple",
  p: "Malachi addresses priests at a working but shabby second temple, accepting blemished animals because no one is watching closely. Into that setting he promises that the Lord will come suddenly to his temple \u2014 to this building, on this platform, at a time when the platform was modest and the ritual half-hearted. The refiner's fire is aimed first at the people running the sanctuary.",
  s: [["zerub", "Malachi 1:10"], ["watergate", "Malachi 3:10"], ["soltemple", "Malachi 3:1", "past"]],
  q: ["Malachi's complaint is about carelessness rather than idolatry. Why is that harder to fix?",
      "The promise is of a sudden arrival at a specific building. Who is it good news for?",
      "What does it mean that judgement begins with the priests?"] },

// ---------------- Book of Mormon ----------------
{ c: "bom", w: 2, r: "1 Nephi 1\u20135", era: "hezekiah", t: "Lehi's Jerusalem, and the way out",
  p: "Lehi leaves about 600 BC, so use the late-monarchy city, not the one Jesus knew: Solomon's Temple on the rock at the north end, the royal quarter below it, the old ridge running south to the spring, and the Western Hill enclosed by Hezekiah's Broad Wall a century earlier. There is no Herodian platform yet, no Upper City of priestly mansions, and no Antonia \u2014 all of that is six centuries away. Lehi goes out by night down the Kidron toward the wilderness. His sons come back for the plates to the house of Laban, a man with a treasury, a servant and armour \u2014 a household of that newer western quarter.",
  s: [["soltemple", "1 Nephi 1:4"], ["royalq", "1 Nephi 3:11"], ["mishneh", "1 Nephi 3:22"], ["cod", "1 Nephi 1:4"], ["kidron", "1 Nephi 2:4"], ["hinnom", "1 Nephi 2:5"]],
  q: ["Lehi's family leaves a city that is prosperous and about to fall. What did that require of them?",
      "Laban's house, treasury and armour suggest real wealth. Which quarter of the 600 BC city would hold such a house \u2014 and why not the Upper City?",
      "The escape route runs downhill and out of the valley. What does that first night cost?"] },

{ c: "bom", w: 3, r: "1 Nephi 6\u201310", era: "hezekiah", t: "A city that will be destroyed",
  p: "Lehi prophesies that Jerusalem will be destroyed and its people carried captive to Babylon, and that they will return. He is describing, in advance, what 586 BC did to the walls and Temple on this map, and what the Return era shows afterwards: a smaller city, a modest second temple, a wall built higher up the slope because the rubble below could not be reused.",
  s: [["soltemple", "1 Nephi 7:13"], ["fishgate", "1 Nephi 7:13"], ["neh", "1 Nephi 10:3", "future"], ["zerub", "1 Nephi 10:3", "future"]],
  q: ["Compare the map's Hezekiah and Return layers. What exactly was lost?",
      "Lehi predicts both destruction and return. Why include the second half?",
      "What made his message unbelievable to people living inside those walls?"] },

{ c: "bom", w: 5, r: "1 Nephi 16\u201322", era: "return", t: "News of the city, from far away",
  p: "By these chapters the family is long gone, and Jerusalem exists in the record as a place they hear about and quote. Nephi's Isaiah chapters are addressed to that city's situation, and 1 Nephi 22 reads them as a promise of gathering. The map is useful here as a control: the small post-exilic city on the ridge is what the prophecies were actually describing.",
  s: [["zion", "1 Nephi 21:14"], ["neh", "1 Nephi 22:12"], ["zerub", "1 Nephi 19:13"], ["cod", "1 Nephi 19:13"]],
  q: ["What changes when prophecies about a city are read by people who will never see it?",
      "Nephi applies Isaiah to his own family's scattering. Is that a fair reading?",
      "How does the size of the real returned city compare with the language used about it?"] },

{ c: "bom", w: 9, r: "2 Nephi 11\u201319", era: "hezekiah", t: "Isaiah's temple vision, quoted whole",
  p: "These chapters carry Isaiah 2\u201312 into the Book of Mormon, including the Temple call in Isaiah 6 and the meeting at the conduit of the upper pool in Isaiah 7. The waters of Shiloah that go softly are the output of the tunnel on this map, and the contrast Isaiah draws is between that quiet local supply and the great river of Assyria that will overflow its banks.",
  s: [["soltemple", "2 Nephi 16:1"], ["siloam", "2 Nephi 17:3"], ["tunnel", "2 Nephi 18:6"], ["gihon", "2 Nephi 18:6"]],
  q: ["Why quote the Temple vision at such length in a record written far from that Temple?",
      "The soft waters of Shiloah versus the river of Assyria \u2014 what is the comparison for?",
      "What does the physical water system add to the metaphor?"] },

{ c: "bom", w: 13, r: "Easter", era: "herod", t: "Two hemispheres, one hour",
  p: "The Book of Mormon's account of the crucifixion is written from the far side of the world, and it dates itself by what happened here. Set the Jerusalem sequence \u2014 the Upper Room, Gethsemane, the trials, Golgotha, the tomb \u2014 beside 3 Nephi 8, and the map supplies the ground that the Nephite record only knows by its effects.",
  s: [["cenacle", "Luke 22:12"], ["gethsemane", "Mark 14:32"], ["golg", "John 19:17"], ["tomb", "John 19:41"], ["temple", "Matthew 27:51"]],
  q: ["What does it mean that one hemisphere felt what happened in a quarter-mile of this city?",
      "The veil of the Temple tore. Where in the building was that veil, and who saw it?",
      "How would you teach the two accounts side by side?"] },

{ c: "bom", w: 42, r: "3 Nephi 20\u201326", era: "herod", t: "Jerusalem promised back",
  p: "Christ quotes Isaiah 52 to the Nephites and then names Jerusalem specifically: the city will be inhabited again by the covenant people, and there will be two gathering places rather than one. He says it to people whose ancestors left that city in a hurry six centuries earlier. The map's Jesus-era and today layers show the same platform in both, which is the geographical point being made.",
  s: [["zion", "3 Nephi 20:29"], ["tm", "3 Nephi 20:33"], ["temple", "3 Nephi 20:36"], ["cod", "3 Nephi 21:23"]],
  q: ["Why does Christ raise Jerusalem with an audience on the other side of the world?",
      "Two gathering places rather than one \u2014 what problem does that answer?",
      "What continuity does the map show between the first-century platform and today's?"] },

{ c: "bom", w: 48, r: "Ether 12\u201315", era: "today", t: "The old Jerusalem and the new",
  p: "Ether 13 sets two cities beside each other: a New Jerusalem to be built in the Americas, and the old Jerusalem which will be built up again, holy, unto the Lord. Moroni is careful to keep them distinct. On the map, the old Jerusalem is a specific square kilometre with an unbroken 3,000-year occupation \u2014 a city that has in fact been rebuilt, repeatedly, on the same rock.",
  s: [["newjer", "Ether 13:5"], ["tm", "Ether 13:11"], ["cod", "Ether 13:11"], ["zion", "Ether 13:3"]],
  q: ["Why does Ether insist on two cities rather than a replacement?",
      "The old city has been destroyed and rebuilt many times. Does that inform the promise?",
      "What is the difference between a city being restored and a city being made holy?"] },

// ---------------- Doctrine and Covenants ----------------
{ c: "dc", w: 19, r: "Doctrine and Covenants 45", era: "today", t: "The Olivet discourse, given again",
  p: "Section 45 retells the Olivet discourse and then extends it. It speaks of Jerusalem trodden down, of the Jews returning, and of the Lord standing on the Mount of Olives so that it cleaves in two \u2014 the same event Zechariah 14 describes. The revelation was given in 1831, when the city was a small Ottoman town of perhaps ten thousand people inside walls three centuries old.",
  s: [["olivet", "D&C 45:48"], ["kidron", "D&C 45:48"], ["tm", "D&C 45:19"], ["temple", "D&C 45:18", "past"], ["zion", "D&C 45:66"]],
  q: ["Section 45 quotes the Olivet discourse and adds to it. What is added?",
      "The revelation describes a Jerusalem the recipients had never seen. What does it assume about that city?",
      "Zechariah 14 and D&C 45:48 describe the same mountain. Why does the location recur?"] },

{ c: "dc", w: 40, r: "Doctrine and Covenants 109\u2013110", era: "today", t: "A prayer in Kirtland, aimed at Jerusalem",
  p: "The Kirtland dedicatory prayer asks that the children of Judah be turned back to the lands of their fathers, and that Jerusalem be redeemed from the desolation laid upon it. The land in question is on this map, and the desolation was visible: in 1836 the Old City had a dwindling population, ruined cisterns and a wall in poor repair. A temple in Ohio prays for a platform in Jerusalem.",
  s: [["tm", "D&C 109:62"], ["zion", "D&C 109:64"], ["temple", "D&C 109:63", "past"], ["kidron", "D&C 109:62"]],
  q: ["Why would a dedicatory prayer in Ohio turn to Jerusalem at all?",
      "The prayer names a desolation. What was the actual state of the city in 1836?",
      "What does it mean to pray for the redemption of a place rather than a people?"] },

{ c: "dc", w: 47, r: "Doctrine and Covenants 133\u2013134", era: "today", t: "Orson Hyde on the Mount of Olives",
  p: "Section 133 speaks of the Lord coming to his temple and of Jerusalem's redemption. Five years later Orson Hyde acted on it: on 24 October 1841 he climbed the Mount of Olives alone, built a small altar of stones, and prayed for the gathering of Judah and the restoration of the land. He chose that summit because it is the one place with the whole city and the whole platform in view \u2014 the same vantage point as the Olivet discourse.",
  s: [["olivet", "D&C 133:20"], ["ascension", "D&C 133:20"], ["tm", "D&C 133:13"], ["golden", "D&C 133:21"], ["kidron", "D&C 133:20"], ["orsongarden", "24 October 1979"]],
  x: { h: "The prayer, and the garden that marks it",
       t: "Hyde had been travelling about eighteen months to reach the city, and arrived alone \u2014 Elder John E. Page had been appointed to go with him and never came, which Hyde notes was exactly what he had seen in vision. His prayer, offered before daylight, asks for three things above all: the gathering of Judah to this land, the building up of Jerusalem, and the rearing of a temple. Around those it asks that the barrenness of the ground be removed and the land made fruitful for its rightful heirs, that kings and nations be inclined to favour the return, and that the kingdom be restored to Israel with Jerusalem as its capital. He then built two altars of stones, one on Olivet and one on Mount Zion, and wrote the prayer out in full in a letter home; it is printed in <em>History of the Church</em> 4:456\u2013459.<br><br>On 24 October 1979 \u2014 the anniversary of that morning \u2014 the Orson Hyde Memorial Garden was dedicated on the same slope by President Spencer W. Kimball, after the Church landscaped the ground and gave it to the city of Jerusalem as a public park. It is terraced with olive trees and paths, has a small amphitheatre looking across the Kidron at the Old City, and looks straight across the Kidron at the Temple platform. The full prayer is printed below and on the second page of this week's handout. Site 6 on the map is the garden; a visitor can stand in it, read the prayer where it was offered, and see the whole platform Hyde was looking at." },
  pray: {
    lead: "Hyde described the morning in a letter to Parley P. Pratt written from Alexandria on 22 November 1841: on Sunday morning, 24 October, a good while before day, he rose, went out of the city as soon as the gates were opened, crossed the brook Kidron, and went up the Mount of Olives \u2014 in solemn silence, with pen, ink, and paper, just as he had seen in vision. Afterwards he raised a pile of stones on the summit of Olivet as a witness, and another on the Temple hill.",
    src: "Orson Hyde to Parley P. Pratt, Alexandria, 22 November 1841; reprinted in <em>History of the Church</em> 4:456\u2013459.",
    t: ["O Thou! who art from everlasting to everlasting, eternally and unchangeably the same, even the God who rules in the heavens above, and controls the destinies of men on the earth, wilt Thou not condescend, through thine infinite goodness and royal favor, to listen to the prayer of Thy servant which he this day offers up unto Thee in the name of Thy holy child Jesus, upon this land, where the Son of Righteousness set in blood, and thine Anointed One expired.","Be pleased, O Lord, to forgive all the follies, weaknesses, vanities, and sins of Thy servant, and strengthen him to resist all future temptations. Give him prudence and discernment that he may avoid the evil, and a heart to choose the good; give him fortitude to bear up under trying and adverse circumstances, and grace to endure all things for Thy name's sake, until the end shall come, when all the Saints shall rest in peace.","Now, O Lord! Thy servant has been obedient to the heavenly vision which Thou gavest him in his native land; and under the shadow of Thine outstretched arm, he has safely arrived in this place to dedicate and consecrate this land unto Thee, for the gathering together of Judah's scattered remnants, according to the predictions of the holy Prophets — for the building up of Jerusalem again after it has been trodden down by the Gentiles so long, and for rearing a Temple in honor of Thy name. Everlasting thanks be ascribed unto Thee, O Father, Lord of heaven and earth, that Thou hast preserved Thy servant from the dangers of the seas, and from the plague and pestilence which have caused the land to mourn. The violence of man has also been restrained, and Thy providential care by night and by day has been exercised over Thine unworthy servant. Accept, therefore, O Lord, the tribute of a grateful heart for all past favors, and be pleased to continue Thy kindness and mercy towards a needy worm of the dust.","O Thou, Who didst covenant with Abraham, Thy friend, and who didst renew that covenant with Isaac, and confirm the same with Jacob with an oath, that Thou wouldst not only give them this land for an everlasting inheritance, but that Thou wouldst also remember their seed forever. Abraham, Isaac, and Jacob have long since closed their eyes in death, and made the grave their mansion. Their children are scattered and dispersed abroad among the nations of the Gentiles like sheep that have no shepherd, and are still looking forward for the fulfillment of those promises which Thou didst make concerning them; and even this land, which once poured forth nature's richest bounty, and flowed, as it were, with milk and honey, has, to a certain extent, been smitten with barrenness and sterility since it drank from murderous hands the blood of Him who never sinned.","Grant, therefore, O Lord, in the name of Thy well-beloved Son, Jesus Christ, to remove the barrenness and sterility of this land, and let springs of living water break forth to water its thirsty soil. Let the vine and olive produce in their strength, and the fig-tree bloom and flourish. Let the land become abundantly fruitful when possessed by its rightful heirs; let it again flow with plenty to feed the returning prodigals who come home with a spirit of grace and supplication; upon it let the clouds distil virtue and richness, and let the fields smile with plenty. Let the flocks and the herds greatly increase and multiply upon the mountains and the hills; and let Thy great kindness conquer and subdue the unbelief of Thy people. Do Thou take from them their stony heart, and give them a heart of flesh; and may the Sun of Thy favor dispel the cold mists of darkness which have beclouded their atmosphere. Incline them to gather in upon this land according to Thy word. Let them come like clouds and like doves to their windows. Let the large ships of the nations bring them from the distant isles; and let kings become their nursing fathers, and queens with motherly fondness wipe the tear of sorrow from their eye.","Thou, O Lord, did once move upon the heart of Cyrus to show favor unto Jerusalem and her children. Do Thou now also be pleased to inspire the hearts of kings and the powers of the earth to look with a friendly eye towards this place, and with a desire to see Thy righteous purposes executed in relation thereto. Let them know that it is Thy good pleasure to restore the kingdom unto Israel — raise up Jerusalem as its capital, and constitute her people a distinct nation and government, with David Thy servant, even a descendant from the loins of ancient David to be their king.","Let that nation or that people who shall take an active part in behalf of Abraham's children, and in the raising up of Jerusalem, find favor in Thy sight. Let not their enemies prevail against them, neither let pestilence or famine overcome them, but let the glory of Israel overshadow them, and the power of the Highest protect them; while that nation or kingdom that will not serve Thee in this glorious work must perish, according to Thy word — Yea, those nations shall be utterly wasted.","Though Thy servant is now far from his home, and from the land bedewed with his earliest tear, yet he remembers, O Lord, his friends who are there, and family, whom for Thy sake he has left. Though poverty and privation be our earthly lot, yet ah! do Thou richly endow us with an inheritance where moth and rust do not corrupt, and where thieves do not break through and steal.","The hands that have fed, clothed, or shown favor unto the family of Thy servant in his absence, or that shall hereafter do so, let them not lose their reward, but let a special blessing rest upon them, and in Thy kingdom let them have an inheritance when Thou shalt come to be glorified in this society.","Do Thou also look with favor upon all those through whose liberality I have been enabled to come to this land; and in the day when Thou shalt reward all people according to their works, let these also not be passed by or forgotten, but in time let them be in readiness to enjoy the glory of those mansions which Jesus has gone to prepare. Particularly do Thou bless the stranger in Philadelphia, whom I never saw, but who sent me gold, with a request that I should pray for him in Jerusalem. Now, O Lord, let blessings come upon him from an unexpected quarter, and let his basket be filled, and his storehouse abound with plenty, and let not the good things of the earth be his only portion, but let him be found among those to whom it shall be said, ‘Thou hast been faithful over a few things, and I will make thee ruler over many.’","O my Father in heaven! I now ask Thee in the name of Jesus to remember Zion, with all her Stakes, and with all her assemblies. She has been grievously afflicted and smitten; she has mourned; she has wept; her enemies have triumphed, and have said, ‘Ah, where is thy God?’ Her Priests and Prophets have groaned in chains and fetters within the gloomy walls of prisons, while many were slain, and now sleep in the arms of death. How long, O Lord, shall iniquity triumph, and sin go unpunished?","Do Thou arise in the majesty of Thy strength, and make bare Thine arm in behalf of Thy people. Redress their wrongs, and turn their sorrow into joy. Pour the spirit of light and knowledge, grace and wisdom, into the hearts of her Prophets, and clothe her Priests with salvation. Let light and knowledge march forth through the empire of darkness, and may the honest in heart flow to their standard, and join in the march to go forth to meet the Bridegroom.","Let a peculiar blessing rest upon the Presidency of Thy Church, for at them are the arrows of the enemy directed. Be Thou to them a sun and a shield, their strong tower and hiding place; and in the time of distress or danger be Thou near to deliver. Also the quorum of the Twelve, do Thou be pleased to stand by them for Thou knowest the obstacles which they have to encounter, the temptations to which they are exposed, and the privations which they must suffer. Give us, therefore, strength according to our day, and help us to bear a faithful testimony of Jesus and His Gospel, to finish with fidelity and honor the work which Thou hast given us to do, and then give us a place in Thy glorious kingdom. And let this blessing rest upon every faithful officer and member in Thy Church. And all the glory and honor will we ascribe unto God and the Lamb forever and ever. Amen."]
  },
  q: ["Why did Orson Hyde choose the Mount of Olives rather than the city itself?",
      "Look at the view from that summit on the map. What could he see while praying?",
      "Read the prayer's petitions about the land itself. Which of them can a visitor now judge by looking?",
      "How does an 1841 prayer on a hillside relate to the prophecies in section 133?"] }
]);
