/* ============================================================
   ADDITIONAL FINDS AND INSCRIPTIONS
   Objects, archives and excavated structures that bear directly
   on the biblical text. Every entry here is one whose reading and
   authenticity are not seriously contested: no suspected forgeries,
   no single-word readings carrying a whole argument, nothing kept
   for its headline value. Where dating rather than authenticity is
   argued — the Jerusalem structures, the Timna mines — the entry
   says which part is debated.
   ============================================================ */

/* the Elephantine papyri were already in the atlas; give them the Persian era too */
(() => {
  const e = FINDS.find(f => f.n === "Elephantine Papyri");
  if (e && !e.e.includes("persia")) e.e.push("persia");
})();

FINDS.push(
  /* ---- patriarchs and the Bronze Age ---- */
  { n:"Egyptian Execration Texts", e:["patriarchs"], date:"c. 1900–1800 BC", found:"Saqqara and Thebes", c:[31.216,29.871],
    where:"Berlin and Brussels museums", w:"Execration_texts", q:"Egyptian execration texts bowl", r:"cf. Gen 12:6; 14:18",
    p:"Egyptian curse texts written on bowls and figurines and then smashed, naming the rulers of Canaanite towns — including forms commonly associated with the earliest known mentions of Jerusalem and Shechem, four centuries before Israel enters the land. They show these places belonged to Egypt's political imagination, but they do not illuminate the historicity of Genesis events." },
  { n:"Mari Letters", e:["patriarchs"], date:"18th c. BC", found:"Tell Hariri (Mari), Syria", c:[40.890,34.550],
    where:"Louvre and Deir ez-Zor Museum", w:"Mari,_Syria", q:"Mari tablets archive", r:"cf. Gen 15; 31",
    p:"Some twenty thousand tablets from an Amorite palace on the middle Euphrates: tribal confederations, covenant rituals involving cut animals, inheritance and adoption customs, and prophets who deliver messages to the king. The nearest thing we have to the social world the patriarchal narratives assume; a broad ancient Near Eastern analogy, not a unique marker that dates Genesis — similar practices persisted across regions and periods." },
  { n:"Alalakh Tablets", e:["patriarchs"], date:"18th–15th c. BC", found:"Tell Atchana, Turkey", c:[36.381,36.239],
    where:"Antakya Archaeological Museum", w:"Alalakh", q:"Alalakh tablets", r:"Gen 37:28",
    p:"Palace archives from a north Syrian city recording slave sales, marriage contracts and treaties. The tablets provide comparative evidence for slave sales and prices in second-millennium north Syria; their prices put a slave in the range of twenty shekels. Genesis 37 also gives a price of twenty shekels for Joseph, but price parallels do not independently date the narrative or exclude later composition — a broad ancient Near Eastern analogy, not a unique marker that dates Genesis." },
  { n:"Beni Hasan Tomb Painting", e:["patriarchs"], date:"c. 1890 BC", found:"Beni Hasan, Egypt", c:[30.876,27.933],
    where:"In situ, tomb of Khnumhotep II", w:"Beni_Hasan", q:"Beni Hasan Asiatics procession painting", r:"Gen 42 – 46",
    p:"A painted procession of thirty-seven Asiatics arriving in Egypt with donkeys, weapons, a lyre and coloured woollen cloaks, labelled as coming from Retjenu. The clearest picture we have of what a Semitic family entering Egypt actually looked like." },
  { n:"The Tale of Sinuhe", e:["patriarchs"], date:"c. 1875 BC", found:"Thebes and Memphis papyri", c:[32.657,25.719],
    where:"Berlin and British Museum papyri", w:"Story_of_Sinuhe", r:"cf. Gen 13; 26",
    p:"An Egyptian courtier flees to Canaan, marries into a local chief's family, and describes the country: figs and vines, barley and emmer, more cattle than he can count, and a life of herding and raiding. Canaan as a literate Egyptian saw it in Abraham's era." },
  { n:"Proto-Sinaitic Inscriptions", e:["exodus"], date:"c. 1800–1500 BC", found:"Serabit el-Khadim, Sinai", c:[33.462,29.038],
    where:"In situ and Egyptian Museum, Cairo", w:"Proto-Sinaitic_script", r:"cf. Exod 17:14; 24:4",
    p:"Short texts scratched by Semitic-speaking workers in Egyptian turquoise mines, using pictographic signs for consonants — the alphabet in the act of being invented, in the Sinai, by the kind of people who could not read hieroglyphs. Writing stops being a scribal profession here." },
  { n:"Papyrus Anastasi", e:["exodus"], date:"13th c. BC", found:"Egypt", c:[32.657,25.719],
    where:"British Museum", w:"Anastasi_I", q:"Papyrus Anastasi", r:"Exod 1:11; 5:6–19; 12:37",
    p:"Egyptian official correspondence: brick quotas and the punishment for missing them, a frontier officer logging Edomite shepherds through the fortress of Tjeku toward the pools of Pithom, and route notes for the coastal road. Delta bureaucracy describing, without comment, the conditions Exodus opens with." },

  /* ---- conquest and judges ---- */
  { n:"Hazor Destruction Layer and Archive", e:["conquest"], date:"c. 13th c. BC", found:"Tel Hazor", c:[35.568,33.017],
    where:"In situ; tablets in the Israel Museum", w:"Tel_Hazor", r:"Josh 11:10–13",
    p:"The largest Canaanite city in the land, burned to the ground with mudbrick fired hard enough to survive: a metre of ash, smashed cult statues with their heads and hands struck off, and cuneiform fragments of its royal correspondence. Who burned it is argued; that it burned is not." },
  { n:"Shiloh Destruction Layer", e:["judges"], date:"c. 1050 BC", found:"Khirbet Seilun", c:[35.289,32.056],
    where:"In situ", w:"Shiloh_(biblical_city)", r:"1 Sam 4; Jer 7:12–14",
    p:"Storerooms full of collared-rim jars, burnt debris and a violent end at about the date 1 Samuel implies for the loss of the ark. Jeremiah's argument centuries later — go and see what I did to Shiloh — turns out to be pointing at something a spade can find." },
  { n:"Izbet Sartah Abecedary", e:["judges"], date:"c. 1200–1000 BC", found:"Izbet Sartah, near Aphek", c:[34.960,32.108],
    where:"Israel Museum", w:"Izbet_Sartah", r:"cf. Judg 8:14",
    p:"An ostracon from a small hill-country village on the Philistine frontier, carrying five lines including the alphabet written out in order — a writing exercise. Ordinary Israelite settlements were learning letters at the very start of the settlement period." },
  { n:"Timna Copper Mines", e:["kingdom","divided"], date:"11th–9th c. BC", found:"Timna valley, Arabah", c:[34.955,29.789],
    where:"In situ, Timna Park", w:"Timna_Valley", r:"cf. Deut 8:9; 1 Kgs 7:45–46",
    p:"Industrial-scale copper smelting camps in the Arabah with organised labour, imported food and fortified gates, radiocarbon dated to the tenth and ninth centuries BC. The metal economy of the early monarchy and Edom — the specific dating and which kingdom ran it are still argued." },

  /* ---- the monarchy ---- */
  { n:"Stepped Stone Structure and Ophel Buildings", e:["kingdom"], date:"10th–9th c. BC (dating debated)", found:"City of David, Jerusalem", c:[35.236,31.774],
    where:"In situ", w:"Stepped_Stone_Structure", r:"2 Sam 5:9; 1 Kgs 9:15",
    p:"A massive terraced retaining structure on the eastern slope and monumental walls above it, holding up the northern end of David's city. Whether these are David's Millo and Solomon's building works or a later Iron Age phase is one of the sharpest dating arguments in the field; the masonry itself is not in doubt." },
  { n:"Tel Rehov Apiary", e:["divided"], date:"c. 900 BC", found:"Tel Rehov, Beth-shean valley", c:[35.498,32.459],
    where:"In situ; reconstruction in the Israel Museum", w:"Tel_Rehov", r:"cf. Deut 8:8; 1 Sam 14:25",
    p:"Over a hundred unfired clay hives stacked in rows in the middle of a city — an industrial apiary capable of producing half a tonne of honey a year, with Anatolian bees. 'A land flowing with milk and honey' turns out to describe an industry, not a metaphor." },
  { n:"Kuntillet Ajrud Inscriptions", e:["divided"], date:"c. 800 BC", found:"Kuntillet Ajrud, northern Sinai", c:[34.406,30.191],
    where:"Israel Museum", w:"Kuntillet_Ajrud", r:"cf. 2 Kgs 17:16; Hos 4:12–13",
    p:"Plaster and pithos inscriptions from a desert way station blessing travellers 'by YHWH of Samaria and his asherah' and 'by YHWH of Teman'. The inscriptions document forms of Yahwistic practice that differ from the exclusive worship urged in many biblical texts; the meaning of asherah here, and the relationship between these inscriptions and particular prophetic passages, remain debated." },
  { n:"Khirbet el-Qom Inscription", e:["divided"], date:"c. 750 BC", found:"Khirbet el-Qom, Judean hills", c:[34.998,31.500],
    where:"Israel Museum", w:"Khirbet_el-Qom", r:"cf. Deut 16:21; 2 Kgs 23:6",
    p:"A tomb inscription for a man named Uriyahu, blessing him by YHWH and 'his asherah' — the same formula as Kuntillet Ajrud, in Judah, cut into a family grave. Evidence that the practice reached the burial of respectable people." },
  { n:"Arad Sanctuary", e:["divided","judah"], date:"9th–7th c. BC", found:"Tel Arad", c:[35.126,31.281],
    where:"In situ; furnishings in the Israel Museum", w:"Tel_Arad", r:"1 Kgs 12:31; 2 Kgs 18:4; 23:8",
    p:"A working Judean temple outside Jerusalem, laid out like the tabernacle's plan, with a sacrificial altar, an incense pair and two standing stones of different heights — then deliberately taken out of use. A state sanctuary and a reform, in one excavated building." },
  { n:"Tel Sheva Horned Altar", e:["judah"], date:"8th c. BC", found:"Tel Sheva (Beersheba)", c:[34.841,31.245],
    where:"Israel Museum", w:"Tel_Be'er_Sheva", r:"2 Kgs 18:4; 23:8; Amos 5:5",
    p:"A large four-horned ashlar altar found dismantled, its stones reused in a later wall. Someone in eighth-century Beersheba pulled down a functioning altar and built its blocks into masonry — a reform of the kind Kings describes, in the debris." },
  { n:"Zakkur Stele", e:["divided"], date:"c. 785 BC", found:"Tell Afis, Syria", c:[36.800,35.900],
    where:"Louvre, Paris", w:"Zakkur_stele", r:"cf. 2 Kgs 13; Amos 1:3–5",
    p:"An Aramaic royal inscription in which Zakkur of Hamath describes being besieged by a coalition under Bar-Hadad of Damascus and rescued after praying — including the line that his god answered him 'by seers and by messengers'. Aramean politics and Aramean prophecy in their own script." },
  { n:"Sefire Treaties", e:["divided"], date:"c. 750 BC", found:"Al-Safirah, near Aleppo", c:[37.100,36.400],
    where:"National Museum of Damascus", w:"Sefire_steles", r:"cf. Deut 28; Lev 26",
    p:"Aramaic treaty steles between an Aramean overlord and his vassal, with witnesses, stipulations and a long list of curses for breaking faith — locusts, drought, mothers eating their children. The literary shape of the covenant curses in Deuteronomy and Leviticus, in a secular contract." },
  { n:"Amman Citadel Inscription", e:["divided"], date:"9th c. BC", found:"Amman citadel", c:[35.934,31.955],
    where:"Jordan Archaeological Museum", w:"Amman_Citadel_Inscription", r:"cf. Judg 11; 2 Sam 12:26–31",
    p:"The oldest substantial text in Ammonite, a building inscription in the name of the god Milkom instructing the king to build and promising protection. Ammon — Israel's neighbour and frequent enemy — speaking its own language about its own god." },
  { n:"Annals of Tiglath-Pileser III", e:["divided"], date:"c. 730 BC", found:"Nimrud (Calah)", c:[43.327,36.099],
    where:"British Museum", w:"Tiglath-Pileser_III", q:"Tiglath-Pileser III annals slab Nimrud", r:"2 Kgs 15:19–29; 16:7–9",
    p:"Assyrian campaign records naming tribute from 'Menahem of Samaria' and 'Jehoahaz [Ahaz] of Judah', and the deportation of Galilee and Gilead. The exact transactions of 2 Kings 15–16, filed by the empire that received the money." },
  { n:"Nimrud Prism of Sargon II", e:["divided"], date:"c. 711 BC", found:"Nimrud (Calah)", c:[43.327,36.099],
    where:"Iraq Museum, Baghdad", w:"Sargon_II", q:"Nimrud prism Sargon II", r:"2 Kgs 17:6; 18:11",
    p:"Sargon's account of taking Samaria, deporting its people and settling foreigners in their place — the other half of 2 Kings 17. Assyrian resettlement changed Samaria's population, but many Israelites remained; the later Samaritan community emerged through a longer, disputed process involving northern Israelite continuity, imperial-period population changes and worship centered on Mount Gerizim. Whether the city fell in 722 or 720 turns on how these annals are read." },
  { n:"Hezekiah Bulla", e:["judah"], date:"c. 700 BC", found:"Ophel, Jerusalem", c:[35.236,31.777],
    where:"Israel Museum, Jerusalem", w:"Seal_of_Hezekiah", r:"2 Kgs 18 – 20",
    p:"A clay seal impression reading 'belonging to Hezekiah [son of] Ahaz, king of Judah', found in a controlled excavation of a royal refuse dump beside the temple mount — the only seal impression of a reigning Judean king recovered in situ." },
  { n:"Bulla of Gemariah son of Shaphan", e:["judah"], date:"c. 600 BC", found:"City of David, Jerusalem", c:[35.236,31.773],
    where:"Israel Museum", w:"City_of_David", q:"bullae house City of David seal impressions", r:"Jer 36:10–12",
    p:"One of fifty-one seal impressions from a burnt administrative room, naming an official who appears by name in Jeremiah 36 as the man whose chamber the scroll was read from. A named minor character in the text, holding a document in the ash." },
  { n:"Broad Wall and the Tower of Hezekiah", e:["judah"], date:"late 8th c. BC", found:"Jewish Quarter, Jerusalem", c:[35.229,31.777],
    where:"In situ", w:"Broad_Wall_(Jerusalem)", r:"Isa 22:9–10; Neh 3:8; 2 Chr 32:5",
    p:"A seven-metre-thick wall thrown across the western hill in haste, cutting straight through houses whose foundations it sits on. Isaiah complains that they pulled down houses to fortify the wall; the wall is still standing on the houses." },
  { n:"Lachish Siege Ramp", e:["judah"], date:"701 BC", found:"Tel Lachish", c:[34.849,31.565],
    where:"In situ", w:"Lachish", q:"Lachish Assyrian siege ramp", r:"2 Kgs 18:14; 2 Chr 32:9",
    p:"The oldest siege ramp known anywhere: nineteen thousand tonnes of stone piled against the southwest corner, with the defenders' counter-ramp inside, arrowheads, sling stones and scale armour in the debris. The ramp shown in Sennacherib's palace relief, on the ground where it was built." },
  { n:"Ramat Rahel Palace", e:["judah"], date:"7th c. BC", found:"Ramat Rahel, Jerusalem", c:[35.212,31.740],
    where:"In situ", w:"Ramat_Rachel", q:"Ramat Rahel palace excavation", r:"cf. 2 Kgs 23:33–35; Jer 22:13–19",
    p:"A palatial administrative compound with Assyrian-style stone capitals, carved window balustrades and a large garden watered by channels, stamped with hundreds of Judean jar seals. A vassal kingdom's administration in the century of Manasseh and Josiah — and the sort of building Jeremiah accuses a king of putting before justice." },
  { n:"Babylonian Destruction Layer, City of David", e:["judah"], date:"586 BC", found:"Jerusalem", c:[35.236,31.773],
    where:"In situ; finds in the Israel Museum", w:"Siege_of_Jerusalem_(587_BC)", q:"City of David 586 BC destruction layer arrowheads", r:"2 Kgs 25:8–10; Lam 1 – 2",
    p:"Collapsed walls, ash, charred beams, smashed storage jars, scattered Scythian-type bronze arrowheads and burnt bullae in buildings along the eastern slope. The end of the kingdom, in a stratum you can put your hand on." },
  { n:"Ashkelon Philistine Cemetery", e:["judges","kingdom"], date:"11th–8th c. BC", found:"Ashkelon", c:[34.560,31.667],
    where:"In situ; study published 2019", w:"Ashkelon", q:"Ashkelon Philistine cemetery excavation", r:"Judg 13 – 16; 1 Sam 5",
    p:"The first substantial Philistine cemetery ever excavated — over two hundred burials — with genetic analysis showing a southern European ancestry component arriving in the twelfth century BC and fading into the local population within a few generations. Israel's defining early enemy, arriving and assimilating, measured." },
  { n:"Judean Shekel Weights and the Pym", e:["judah"], date:"8th–7th c. BC", found:"across Judah", c:[35.100,31.700],
    where:"Israel Museum and others", w:"Shekel", q:"Judean stone shekel weights pym", r:"1 Sam 13:21; Deut 25:13–15; Amos 8:5",
    p:"Small inscribed limestone weights in a standard system — shekel multiples, and the two-thirds unit called a pym. Inscribed pym weights helped confirm that the term in 1 Samuel 13:21 denotes a unit of approximately two-thirds of a shekel; the prophets' complaints about false weights are about these objects." },

  /* ---- exile, Persia and the intertestamental centuries ---- */
  { n:"Murashu Archive", e:["exile","persia"], date:"455–403 BC", found:"Nippur", c:[45.238,32.126],
    where:"Istanbul and University of Pennsylvania", w:"Murashu_archive", r:"cf. Ezra 2; Neh 7",
    p:"Some seven hundred business tablets of a Babylonian firm of land agents, recording leases, loans and taxes — with dozens of clients bearing Yahwistic names. Judeans who stayed in Babylonia after the return, farming irrigated land under Persian administration, in ordinary commercial paperwork." },
  { n:"Persepolis Fortification Tablets", e:["exile","persia"], date:"509–494 BC", found:"Persepolis", c:[52.891,29.935],
    where:"Iran and the University of Chicago", w:"Persepolis_Administrative_Archives", r:"cf. Est 1 – 3; Ezra 6",
    p:"Tens of thousands of Elamite administrative tablets recording rations, travel authorisations and payments across the empire — including sealed travel documents of the kind Nehemiah asks the king for. The machinery behind the Persian court scenes of Esther and Ezra." },
  { n:"Wadi Daliyeh Papyri", e:["persia","hellenistic"], date:"375–335 BC", found:"cave in Wadi Daliyeh, near Jericho", c:[35.400,32.000],
    where:"Israel Museum", w:"Wadi_Daliyeh", q:"Wadi Daliyeh papyri Samaria", r:"cf. Neh 4; 13",
    p:"Aramaic slave-sale deeds and sealings carried out of Samaria by refugees who hid in a cave and were killed there as Alexander's forces came through. Samaria's own administrative records, naming its governors — and the last documents of the Persian province." },
  { n:"Tobiah Inscriptions at Iraq el-Amir", e:["persia"], date:"4th–3rd c. BC", found:"Iraq el-Amir, Jordan", c:[35.756,31.911],
    where:"In situ", w:"Iraq_al-Amir", q:"Iraq el-Amir Tobiah inscription", r:"Neh 2:10; 4:3; 6:1–14",
    p:"The name Tobiah carved in Aramaic letters at the entrance to a rock-cut complex in Ammonite country, the seat of the Tobiad family. Nehemiah's most persistent opponent belonged to a dynasty that left its name on its own estate." },
  { n:"Zenon Papyri", e:["hellenistic"], date:"c. 260–240 BC", found:"Philadelphia, Fayum, Egypt", c:[30.900,29.450],
    where:"Cairo, Michigan and London collections", w:"Zenon_Papyri", q:"Zenon papyri Ptolemaic archive", r:"cf. Dan 11:5",
    p:"The business archive of a Ptolemaic estate manager, including correspondence about grain, slaves and taxes in Palestine and dealings with the Tobiad family in Transjordan. Everyday Ptolemaic administration of Judea's neighbourhood, in the century before the Maccabees." },
  { n:"Proposed Akra Remains", e:["hasmonean"], date:"2nd c. BC", found:"Givati parking lot, Jerusalem", c:[35.235,31.773],
    where:"In situ", w:"Acra_(fortress)", q:"Givati parking lot Seleucid fortification Jerusalem", r:"cf. Dan 11:31", cf:"disputed",
    p:"A massive sloping fortification wall with a tower, ballista stones, sling shot and Seleucid coins of Antiochus IV and his successors, on the slope below the temple mount. Excavators have identified these fortifications with the Akra described in 1 Maccabees; the proposal is prominent but not universally accepted, and the fortress's precise location remains debated." },
  { n:"Temple Mount Balustrade Inscription", e:["roman"], date:"Herodian period, late 1st c. BC – 1st c. AD", found:"Jerusalem", c:[35.235,31.778],
    where:"Istanbul Archaeological Museums", w:"Temple_Warning_inscription", r:"cf. Ezek 44:9",
    p:"A Greek inscription from the low barrier around Herod's temple courts warning that no foreigner may pass beyond it. The physical boundary of the sanctuary's inner precinct, in the language most visitors read." },
  { n:"The Place of Trumpeting Stone", e:["roman"], date:"1st c. BC", found:"Southwest corner, Temple Mount", c:[35.234,31.776],
    where:"Israel Museum, Jerusalem", w:"Trumpeting_Place_inscription", r:"cf. Num 10:10; Ps 81:3",
    p:"A carved parapet block from the top of Herod's platform, inscribed 'to the place of trumpeting', found in the rubble where it fell. The spot where a priest stood to sound the sabbath — architecture confirming a practice." },
  { n:"Herodian Coinage", e:["roman"], date:"37–4 BC", found:"Judea", c:[35.235,31.776],
    where:"Israel Museum and others", w:"Herodian_coinage", r:"cf. Exod 20:4",
    p:"Bronze coins of Herod the Great carrying anchors, tripods, cornucopiae and a Greek legend. Herod generally avoided royal portraiture and favored such symbols, consistent with sensitivity to Jewish aniconic concerns; coin types varied, and this was not a universal rule among all client kings of Rome." }
);
